### ISSUE TITLE
求助_求助_求助

### ISSUE THREAD

**Issue by Guollove** [xaoxuu/hexo-theme-stellar#101]
![52D16E0901F896E6DE728744A6035287](https://user-images.githubusercontent.com/53716683/174117245-b542bdd4-c914-4006-889d-097813af0279.jpg)

是我太笨了。研究三天啦。还有两个部分功能死活找不到
第一个。 侧边栏这么把它弄成这种小标签形式
第二个。 Sites（网站卡片标签）怎么让他分组 也有title标题  搞一天了。title标题老是冲突。

是在没办法了。只好求助了。 谢谢🙏解答。谢谢了。 谢谢。

**Comment by xaoxuu** [comment]
请问您知道文档在哪吗？

**Comment by xaoxuu** [comment]
https://xaoxuu.com/wiki/stellar/wiki-settings/#%E5%AF%B9%E7%9B%AE%E5%BD%95%E6%A0%91%E8%BF%9B%E8%A1%8C%E5%88%86%E7%BB%84
