### ISSUE TITLE
关于修改样式的问题

### ISSUE THREAD

**Issue by Fiuck** [xaoxuu/hexo-theme-stellar#11]
我是通过npm i hexo-theme-stellar下载的，theme下面没有stellar的主题包，只在node_modules下面有。现在我如果想自定义样式的话我应该怎么做呢

**Comment by xaoxuu** [comment]
不同的安装方式适合不同的人群，详见文档：
![image](https://user-images.githubusercontent.com/16400144/121621833-87176400-ca9f-11eb-9054-e323fe7e8d63.png)
