### ISSUE TITLE
如何自定义footer里自带的文本

### ISSUE THREAD

**Issue by bit704** [xaoxuu/hexo-theme-stellar#114]
您好！谢谢您优秀的主题。

我想知道如何自定义footer里自带的文本（修改其内容），如图中红框所示：

![footer](https://tvax4.sinaimg.cn/large/0077Un8Egy1h5glo9dkx4j30mv059jsm.jpg)

因为图中有一个小问题：由于使用mathjax和pandoc替换掉了marked（要渲染数学公式），footer里的markdown没有正确渲染。我想修改其内容。

**Comment by xaoxuu** [comment]
暂时不支持配置修改，可以自行修改主体源码

**Comment by xaoxuu** [comment]
现在可以全部自定义了
