### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dc932dc** [xaoxuu/hexo-theme-stellar#116]

**Comment by xaoxuu** [comment]
那三个点没有实际功能，实际上它们分别代表关闭窗口、最小化窗口、最大化窗口，放在这里有迷惑性，喜欢的话建议自己尝试DIY

**Comment by xaoxuu** [comment]
![](https://user-images.githubusercontent.com/16400144/190126148-97801084-ff0c-4a43-bb7e-e91bc7ebc70d.png)
苹果这边是有个细细的边框的

**Comment by Cubik65536** [comment]
> ![](https://user-images.githubusercontent.com/16400144/190126148-97801084-ff0c-4a43-bb7e-e91bc7ebc70d.png)
> 苹果这边是有个细细的边框的

我是知道的，但是目前好像很少有方案是把边框做出来的，也就都只是为了就看着差不多像而做的更改

**Comment by Cubik65536** [comment]
我这边重新整理了一下主题分支，去掉了很多以前没用的东西，如有需要请参考这两个 commit（仍然不算完美效果）

- https://github.com/Cubik65536/cubik-website-theme/commit/77fbf2776bd208359616b6a42dc3d456459f221b
- https://github.com/Cubik65536/cubik-website-theme/commit/e07517b6541fe0aa3f1e0c61a97e82cfbcfd5ea6

已知问题有两个：
- 没有上面的边框
- 如果字体与我的设置不一样（包括字型以及大小的设置），显示效果可能会不一，可能需要自己调整，暂时没有太多精力去调整所以抱歉
