### ISSUE TITLE
提供主题配色切换

### ISSUE THREAD

**Issue by XuxuGood** [xaoxuu/hexo-theme-stellar#12]
![image](https://user-images.githubusercontent.com/45960164/124342833-8a62c300-dbf9-11eb-92aa-b007012f5ac8.png)
类似这个样子，不知道有没有兴趣搞一哈大佬

**Comment by xaoxuu** [comment]
博客网站不是程序，没人会在只需要看一篇文章的网站上找设置的，越无感越好，跟随系统切换就已经足够了。

**Comment by flechazoyang-google** [comment]
请问可以关掉随系统切换吗，固定使用light主题
