### ISSUE TITLE
使用 Swiper 标签的图片在放大后会重复出现三次

### ISSUE THREAD

**Issue by i-abc** [xaoxuu/hexo-theme-stellar#120]
如图所示，使用 Swiper 标签的图片重复出现了三次：

![image](https://user-images.githubusercontent.com/104631897/193287152-446b9f13-2c05-42ab-adaf-76bb62b2a4b6.png)

复现：[https://www.shifeiti.com/blog/2022-09-19/](https://www.shifeiti.com/blog/2022-09-19/)

**Comment by xaoxuu** [comment]
我觉得可能是插件本身为了无限循环而重复放置的

**Comment by i-abc** [comment]
> 我觉得可能是插件本身为了无限循环而重复放置的

我感觉不是这样的。

在这里我使用了`image`标签，未重复：
![image](https://user-images.githubusercontent.com/104631897/198241524-ec1f2f2b-59ed-441d-9cce-a25a03731478.png)
复现链接：[https://www.shifeiti.com/blog/2022-10-13/](https://www.shifeiti.com/blog/2022-10-13/)

在这里我使用了`Swiper`标签，重复了三次，而且左上角计数也体现出来重复了三次（我原本只有6张图）：
![image](https://user-images.githubusercontent.com/104631897/198242222-9adeeeea-7b67-495d-af06-22ad9a36d524.png)
复现链接：[https://www.shifeiti.com/blog/2022-09-19/](https://www.shifeiti.com/blog/2022-09-19/)

**Comment by xaoxuu** [comment]
> 我觉得可能是插件本身为了无限循环而重复放置的

@i-abc 额，我这里指的就是 `swipe` 插件，你在项目里搜 `loop: true` 改为 `loop: false` 试一下。

**Comment by i-abc** [comment]
> > 我觉得可能是插件本身为了无限循环而重复放置的
> 
> @i-abc 额，我这里指的就是 `swipe` 插件，你在项目里搜 `loop: true` 改为 `loop: false` 试一下。

还真是，改为 `loop: false` 就好了。

**Comment by xaoxuu** [comment]
设为false就不能无限循环滚动了，可能要自己做个取舍了
