### ISSUE TITLE
近期的 “text-align: justify” 更改，可能會讓文章變得十分難以閱讀

### ISSUE THREAD

**Issue by pan93412** [xaoxuu/hexo-theme-stellar#132]
a25b1701c58444c0fca6afbd05081ae9560f20e7 提交中，將所有沒有 class 的 `p` 都套用上 `text-align: justify`。這導致某些**有連結的**長句的字距被拉得太開：

<img width="713" alt="image" src="https://user-images.githubusercontent.com/28441561/197572641-0d86e9df-866c-497d-812a-8d28fd1f3f31.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/28441561/197572448-f4ebe95c-ecca-43bf-bc31-dbcd71751e21.png">

恢復到預設 `text-align: left;` 模式便好多了：

<img width="756" alt="image" src="https://user-images.githubusercontent.com/28441561/197572795-cfaa24be-3b98-4b86-ab9c-1d69f6ea530f.png">

<img width="755" alt="image" src="https://user-images.githubusercontent.com/28441561/197572956-34ad38ad-6c13-4fa6-a226-456f3c1c59a0.png">

我猜是 `justify` 演算法不適合有連結的場景。感覺用 utility class 選擇性讓使用者啟用/停用要 justify 的 paragraph 會更好。

**Comment by xaoxuu** [comment]
刚增加了配置选项 https://github.com/xaoxuu/hexo-theme-stellar/commit/8301b75ee290d7cdea9cb8ba8ef8aec83aec7144 ，不过更加建议缩短链接长度，避免直接显示链接本体：
> 建议： This is a [link](https://github.com/xaoxuu/hexo-theme-stellar)
> 不建议： This is a link: https://github.com/xaoxuu/hexo-theme-stellar

**Comment by pan93412** [comment]
> 刚增加了配置选项 https://github.com/xaoxuu/hexo-theme-stellar/commit/8301b75ee290d7cdea9cb8ba8ef8aec83aec7144 ，不过更加建议缩短链接长度，避免直接显示链接本体：
> > 建议： This is a [link](https://github.com/xaoxuu/hexo-theme-stellar)
> > 不建议： This is a link: https://github.com/xaoxuu/hexo-theme-stellar
> 

覺得做成可以以段落為單位的 class 可以更好：

```html
<p class="u-left">這段有很長很長的連結</p>
<p>其餘情況可以維持 justify，獲得更好的閱讀體驗</p>
```

**Comment by weekdaycare** [comment]
同时`waline`评论区也会跟随`text-align`设置变成这样
![image](https://user-images.githubusercontent.com/63026074/197701578-0ba50ff6-4d92-40c6-912c-8acdad11f563.png)

**Comment by xaoxuu** [comment]
> 同时`waline`评论区也会跟随`text-align`设置变成这样 ![image](https://user-images.githubusercontent.com/63026074/197701578-0ba50ff6-4d92-40c6-912c-8acdad11f563.png)

我限制一下只影响文章区域吧
