### ISSUE TITLE
【建议】：朋友文章增加默认头像

### ISSUE THREAD

**Issue by i-abc** [xaoxuu/hexo-theme-stellar#137]
希望朋友文章能增加默认头像，当某个头像不能显示的时候可以自动替换，就像友链中的做法一样：

![image](https://user-images.githubusercontent.com/104631897/198825445-1b3a423d-6ba6-4c35-bf37-6f1c53099675.png)

![image](https://user-images.githubusercontent.com/104631897/198825491-fff5014c-1bc2-425e-a795-6f95d59833b6.png)

**Comment by xaoxuu** [comment]
已加 https://github.com/xaoxuu/hexo-theme-stellar/commit/e929a33351bc864b423d1dfb6f4917ae773abcd1

**Comment by i-abc** [comment]
太快了🎉

**Comment by xaoxuu** [comment]
另外，截图中那烦人的滚动条能不能帮我隐藏一下，我这边都是苹果看不到滚动条。。。也没法调试

**Comment by i-abc** [comment]
> 另外，截图中那烦人的滚动条能不能帮我隐藏一下，我这边都是苹果看不到滚动条。。。也没法调试

抱歉，这个我也帮不上忙，我不懂编程，博客全是看你的 wiki 搭的
