### ISSUE TITLE
[分享] Stellar主题自定义侧边栏教程「萌新向」

### ISSUE THREAD

**Issue by skyreeves** [xaoxuu/hexo-theme-stellar#138]
**[Stellar主题自定义侧边栏教程「萌新向」](https://skyreeves.com/post/9b8cc433.html)**

为了避免和我一样的萌新走弯路，也为了避免自己忘记，现将我自定义侧边栏的过程记录成册供以后翻阅

**Comment by Nakagawa-Chinatsu** [comment]
@skyreeves 
可否问一下你的博客背景是怎样设计的

**Comment by skyreeves** [comment]
@Nakagawa-Chinatsu 
在 `themes/hexo-theme-stellar/layout/layout.ejs` 文件中添加如下代码：

```ejs
<!--动态线条背景-->
<script type="text/javascript"
color="220,220,220" opacity='0.7' zIndex="-2" count="200" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js">
</script>
```

其中：

- color：表示线条颜色，三个数字分别为(R,G,B)，默认：（0,0,0）
- opacity：表示线条透明度（0~1），默认：0.5 
- zIndex：表示背景的z-index属性，css属性用于控制所在层的位置，默认：-1
-  count：表示线条的总数量，默认：150

**Comment by Nakagawa-Chinatsu** [comment]
@skyreeves thanks！已经可以了，谢谢帮助
