### ISSUE TITLE
朋友圈api问题

### ISSUE THREAD

**Issue by cyolc932** [xaoxuu/hexo-theme-stellar#147]
大佬 我参考该教程：https://xaoxuu.com/wiki/stellar/advanced-settings/#%E5%8F%8B%E9%93%BE%E6%9C%8B%E5%8F%8B%E5%9C%88
fork了您的仓库：[@xaoxuu/friends-rss](https://github.com/xaoxuu/friends-rss)
这是我的朋友圈fork仓库：https://github.com/cyolc932/friends-rss

在api这一块不太理解 
![图片](https://user-images.githubusercontent.com/46415893/199194890-7481a6ac-f2b4-452f-ba99-d390d42c3ab1.png)
我将其修改为
---
api:https://raw.github.xaoxuu.com/cyolc932/friends-rss/output/data.json
---
昨日发现朋友圈还能用，今天就无法使用了。
![图片](https://user-images.githubusercontent.com/46415893/199195175-f453c31d-07d8-4106-b3c9-b45ad00df7b8.png)
您方便帮我看看吗？
我的朋友圈地址：https://blog.cyolc932.eu.org/friends/rss/

**Comment by weekdaycare** [comment]
你好，为了规避潜在vercel滥用风险，原来的api已失效，请更新你的`api:https://raw.githubusercontent.com/cyolc932/friends-rss/output/data.json`

**Comment by cyolc932** [comment]
> 你好，为了规避潜在vercel滥用风险，原来的api已失效，请更新你的`api:https://raw.githubusercontent.com/cyolc932/friends-rss/output/data.json`

噢噢好的感谢 大佬您的教程也许该更新一下api了😄
https://xaoxuu.com/wiki/stellar/advanced-settings/#%E5%8F%8B%E9%93%BE%E6%9C%8B%E5%8F%8B%E5%9C%88

**Comment by weekdaycare** [comment]
啊，我不是作者大大，这个api是今天改的，所以文档还没及时更新

**Comment by xaoxuu** [comment]
是的，我的东西不给别人用了，你可以自己想办法加速哦
