### ISSUE TITLE
Not knowing how to show "about" page 

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#148]
![image](https://user-images.githubusercontent.com/68626438/199195731-67dfa287-5beb-477f-8650-0c0721f6fc98.png)

**Comment by weekdaycare** [comment]
你的source文件夹下有about文件夹吗？在about文件夹中新建`index.md`编写该文档即可

**Comment by deskside** [comment]
谢谢解答！
