### ISSUE TITLE
post-index没有高亮

### ISSUE THREAD

**Issue by felixchen0707** [xaoxuu/hexo-theme-stellar#150]
按照文档配置了友链朋友圈，遇到一个问题，当正在浏览友链朋友圈页面时，导航栏处不会高亮(`class=active`)，请问该如何设置。
![image](https://user-images.githubusercontent.com/99467198/199191181-b32d6ebc-6794-4d04-803a-cb0cea644325.png)
复现链接：[朋友文章](https://blog.felixchen0707.cn/link/rss/)
我的配置：
`source/link/rss/index.md`:
```markdown
---
seo_title: 朋友文章
# robots: noindex, nofollow
menu_id: post
comments: false
post_list: true
sidebar: [welcome, recent]
---

{% timeline type:fcircle api:https://fcircle.felixchen0707.cn/all %}
{% endtimeline %}
```
`_config.stellar.yaml`
```yaml
######## Index ########
post-index: # 近期发布 分类 标签 归档 and ...
  '朋友文章': /link/rss/
```
另外stellar有没有用户群呐

**Comment by xaoxuu** [comment]
发一下链接看看呢

**Comment by felixchen0707** [comment]
我在[这里](https://github.com/xaoxuu/hexo-theme-stellar/discussions/146)回啦，这个issue我就关掉了
