### ISSUE TITLE
How to change @ info in the page footer? 如何修改页面底部的@信息？

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#153]
请问如何更改底部的这段文字中的@部分呢？

![image](https://user-images.githubusercontent.com/68626438/199374850-42c41ab2-290f-4625-90ae-4cd2e5bd3a1f.png)

**Comment by weekdaycare** [comment]
自行更改'_config.stellar.yml' footer中的content

**Comment by deskside** [comment]
@weekdaycare 你好，感谢答复！我没有找到` _config.stellar.yml` 的范例footer内容，请问可以分享一下范例代码吗？

**Comment by weekdaycare** [comment]
首先你的版本要在[1.10.0](https://github.com/xaoxuu/hexo-theme-stellar/releases/tag/1.10.0)以上，然后
<details>
<summary>官方示例</summary>
######## Footer ########
footer:
  social:
    # github:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
    #   url: /
    # music:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
    #   url: /
    # unsplash:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
    #   url: /
    # comments:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
    #   url: /about/#comments
  sitemap:
    # '博客':
    #   - '[近期](/)'
    #   - '[分类](/)'
    #   - '[标签](/)'
    #   - '[归档](/)'
    # '项目':
    #   - '[开源库](/)'
    # '社交':
    #   - '[友链](/)'
    #   - '[留言板](/)'
    # '更多':
    #   - '[关于本站](/)'
    #   - '[GitHub](/)'
  content: | # 支持 Markdown 格式
    本站由 [@anonymity](/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
  # 主题用户越多，开发者维护和更新的积极性就越高，如果您喜欢本主题，请在适当的位置显示主题信息和仓库链接以表支持。
</details>

**Comment by xaoxuu** [comment]
@deskside 默认的在主题的 `_config.yml` 里

**Comment by deskside** [comment]
> @deskside 默认的在主题的 `_config.yml` 里

@xaoxuu 感谢您的答复！我找到了~

也十分感谢 @weekdaycare 的答复！
