### ISSUE TITLE
作为小白，我要在 config.yml文件那个位置，更换头像呢？

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#155]

**Comment by xaoxuu** [comment]
```yaml
avatar: /xxx/xx.jpg
```

**Comment by xaoxuu** [comment]
对小白最实用的建议：先阅读 [官方文档](https://hexo.io/zh-cn/docs/)

**Comment by abnerwei** [comment]
> _No description provided._

建议阅读大佬的[主题文档](https://xaoxuu.com/wiki/stellar/widgets/#Logo)

**Comment by czsmall** [comment]
> ```yaml
> avatar: /xxx/xx.jpg
> ```

了解
