### ISSUE TITLE
[分享] 利用 Github 博客仓分支备份博客源文件

### ISSUE THREAD

**Issue by skyreeves** [xaoxuu/hexo-theme-stellar#156]
**[利用 Github 博客仓分支备份博客源文件](https://www.skyreeves.cn/2022/11/03/利用%20Github%20博客仓分支备份博客源文件/)**

受[@星日语](https://weekdaycare.cn)大佬[Stellar更新&备份](https://weekdaycare.cn/posts/stellar-update/)教程的启发，在blog所在仓里新建分支，实现通过 `hexo d` 部署静态网页至 `main` ， `git push` 备份源文件至新分支。

**Comment by xaoxuu** [comment]
我把标签去掉就好了
