### ISSUE TITLE
较新/较早文章为封面文章时，可能出现文章标题展示为 undefined

### ISSUE THREAD

**Issue by abnerwei** [xaoxuu/hexo-theme-stellar#159]
1. 现象
当下一篇文章为全封面文章时，由于没有`title`可能导致文章标题为`undefined`
![image](https://user-images.githubusercontent.com/19216484/199873596-e025f615-3647-4f71-ad6e-c91d05f7ce9f.png)

3. 问题
https://github.com/xaoxuu/hexo-theme-stellar/blob/3a4e1663efe184cc5d15a9390f999efb31f5c913/layout/_partial/main/article/read_next.ejs#L47

**Comment by xaoxuu** [comment]
发一下你的文章链接，我看看是使用方式不合适还是确实有不需要标题的需求。

**Comment by xaoxuu** [comment]
因为 `title` 和 `seo_title` 至少要有一个，否则页面就没有标题了，如果连页面标题都不在乎了，那我觉得这里显示 undefined 似乎也不会在乎了。

**Comment by abnerwei** [comment]
> 因为 `title` 和 `seo_title` 至少要有一个，否则页面就没有标题了，如果连页面标题都不在乎了，那我觉得这里显示 undefined 似乎也不会在乎了。

是的，当后一篇文章改成全封面的文章时，因为一些情况，只设置了`cover`和`cover-title`或`cover-subtitle`，没有设置`seo_title`，才会导致这种情况

**Comment by xaoxuu** [comment]
我看到了， https://abnerwei.com/post/aeebbcec/ 这篇文章没有标题，你需要设置一个标题，`cover`相关的属性是文章宣传封面，是可有可无的东西，`cover-title`不能替代原有的文章标题，后续我再改下名字防止引起误解吧。你可以理解为封面图片、封面上的大字、封面上的小字，它跟文章标题是无关的。

**Comment by abnerwei** [comment]
> 我看到了， https://abnerwei.com/post/aeebbcec/ 这篇文章没有标题，你需要设置一个标题，`cover`相关的属性是文章宣传封面，是可有可无的东西，`cover-title`不能替代原有的文章标题，后续我再改下名字防止引起误解吧。你可以理解为封面图片、封面上的大字、封面上的小字，它跟文章标题是无关的。

ok，开始时候直接把`title`改成`cover-title`，同时没设置`seo-title`，发现这种情况了

**Comment by xaoxuu** [comment]
大概要改成这样：
```yaml
cover: # 原封面图片不变
poster: # 海报（即全图封面样式卡片），设置了此项会取cover作为海报背景
  topic: # 封面大字上方的简短小字
  headline: # 封面大字
  caption: # 封面大字下方的描述
```
