### ISSUE TITLE
这种侧边栏目录怎么做的。文档我看不太懂！

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#160]

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/199920662-e1638f35-2e7e-4b8e-915d-05163fa32496.png)

**Comment by czsmall** [comment]
在那个配置里面加？

**Comment by xaoxuu** [comment]
https://www.skyreeves.cn/2022/10/28/Stellar%E4%B8%BB%E9%A2%98%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BE%A7%E8%BE%B9%E6%A0%8F%E6%95%99%E7%A8%8B%E3%80%8C%E8%90%8C%E6%96%B0%E5%90%91%E3%80%8D/
