### ISSUE TITLE
请问如何设置中英文双语切换？How to set CN/EN language switchable in Stellar? 

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#161]
如题，感谢！

**Comment by xaoxuu** [comment]
不支持动态切换呢？内置的文案可以通过改配置文件的语言顺序修改语音。

**Comment by deskside** [comment]
@xaoxuu 谢谢，了解了！请问未来会有规划这个功能吗？

**Comment by xaoxuu** [comment]
暂时没有这个计划呢，目前用户绝大部分都是简体中文用户，少量繁体中文用户，喜欢的话可以自己弄一下，其他主题都有，应该有源码可以参考的。

**Comment by deskside** [comment]
谢谢！感恩您的解答！

**Comment by deskside** [comment]
![image](https://user-images.githubusercontent.com/68626438/200156674-7c3e0907-43fd-4a5b-b159-5b58fe6a0412.png)

想到了如果是文章的话可以通过这种方式进行中英文切换曲线救国哈哈~
