### ISSUE TITLE
边栏最下面的小图标。在那个地方直设置。。。看了文档没找到！！

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#163]

**Comment by xaoxuu** [comment]
```yaml
footer:
  social:
    ...
```

**Comment by czsmall** [comment]
> 

在那个地方 那个配置写？

**Comment by czsmall** [comment]
这么简介的答复，，完全看不懂

**Comment by xaoxuu** [comment]
> ```yaml
> footer:
>   social:
>     ...
> ```

你文件里搜一下搜不到这个地方吗？

**Comment by czsmall** [comment]
指下配置文档 在那个目录也行

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/blob/f59d3228e2a34ea0b4c3220288171c25e92b4199/_config.yml#L159-L172

**Comment by czsmall** [comment]
感谢博客！

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200118316-e8fef611-b2d1-4062-b09e-ec17ee44083d.png)

**Comment by czsmall** [comment]
在打扰下。。。这个侧边栏，照片轮询显示。。我要在这么加配置呢！

**Comment by xaoxuu** [comment]
不支持照片轮询显示

**Comment by i-abc** [comment]
> 在打扰下。。。这个侧边栏，照片轮询显示。。我要在这么加配置呢！

照片轮询显示是我调用的一个随机图片 api，和主题设置无关
![](https://acgapi.shifeiti.com/api)

**Comment by czsmall** [comment]
> > 在打扰下。。。这个侧边栏，照片轮询显示。。我要在这么加配置呢！
> 
> 照片轮询显示是我调用的一个随机图片 api，和主题设置无关 ![](https://camo.githubusercontent.com/4120b7be4cca048164af6a9761c70b57a9feb23ef39dc331888182e4e84edc82/68747470733a2f2f6163676170692e73686966656974692e636f6d2f6170692e706e67)

方便细说，或者指导一下嘛？

**Comment by czsmall** [comment]
> 不支持照片轮询显示

假如加照片不轮询。添加的格式是怎么样的？

**Comment by i-abc** [comment]
> > > 在打扰下。。。这个侧边栏，照片轮询显示。。我要在这么加配置呢！
> > 
> > 
> > 照片轮询显示是我调用的一个随机图片 api，和主题设置无关 ![](https://camo.githubusercontent.com/4120b7be4cca048164af6a9761c70b57a9feb23ef39dc331888182e4e84edc82/68747470733a2f2f6163676170692e73686966656974692e636f6d2f6170692e706e67)
> 
> 方便细说，或者指导一下嘛？

你百度吧，关键词`随机图片api`

**Comment by czsmall** [comment]
> > 不支持照片轮询显示
> 
> 假如加照片不轮询。添加的格式是怎么样的？

对待小白，多点耐心呗

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200119257-be27667a-a09d-411a-9988-5df93364656c.png)

添加格式是什么样式

**Comment by i-abc** [comment]
> ![image](https://user-images.githubusercontent.com/110958481/200119257-be27667a-a09d-411a-9988-5df93364656c.png)
> 
> 添加格式是什么样式

```yaml
welcome:
  layout: markdown
  title: '记录生活，热爱跑步，学习 FPGA 中。'
  content: |
    一个人只拥有此生此世是不够的，他还应该拥有诗意的世界。
    ![](https://www.dmoe.cc/random.php)
```
Hexo 需要自己多尝试，多 `hexo cl && hexo g && hexo s`。

**Comment by czsmall** [comment]
@xaoxuu
@i-abc 多了不说 ，，感谢你们！！！
