### ISSUE TITLE
项目图标logo无法显示

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#164]
![image](https://user-images.githubusercontent.com/68626438/200124128-97320c04-b6cc-460b-aa9d-f4d98701e88d.png)

理论上我已经将项目图标放在了指定位置，按照配置文件里的要求填写了，但是无论怎么样都无法正常显示。

除了svg，我还试了png图片也不行。我还试过更改图片位置也不行。麻烦大佬了。

**Comment by weekdaycare** [comment]
logo: /wiki/EmoDiary/happy-face.svg

**Comment by deskside** [comment]
@weekdaycare 搞定了！太感谢了！

那[范例代码](https://xaoxuu.com/wiki/stellar/wiki-settings/)里的「是否显示封面」部分的代码是否也需要做出修改呢~

**Comment by xaoxuu** [comment]
资源在 `blog/source/assets/xxx` 里面放着的呢，跟 `md` 文件不在一个地方。

**Comment by weekdaycare** [comment]
对的，图片路径是相对于`source`文件夹的

**Comment by deskside** [comment]
原来是这样，学习到了！感谢解答~
