### ISSUE TITLE
如图，我的便签页如何才能像他们一起。左上角显示头像？

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#165]

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200169365-d275f8be-1932-4086-9d26-f65896f78519.png)

**Comment by weekdaycare** [comment]
找 1.11.0 版本的源码进行替换
文件路径是 `themes/stellar/layout/_partial/sidebar/logo.ejs`

**Comment by deskside** [comment]
@weekdaycare  请问我的这个路径没有相关文件，怎么解决呀~

![image](https://user-images.githubusercontent.com/68626438/200175025-a0e89520-666a-418e-aab6-b017f19c8539.png)

**Comment by weekdaycare** [comment]
你是用稳定版安装的吧，那不建议改动源文件，后续升级就有点麻烦，若执意要更改的话
路径在这里 `blog/node_modules/hexo-theme-stellar/layout/_partial/sidebar/logo.ejs`

**Comment by weekdaycare** [comment]
@czsmall @deskside 大大刚刚更新了，最新版代码支持显示头像了
![image](https://user-images.githubusercontent.com/63026074/200175916-8b173b7e-8da5-47db-95a2-9edd37e85562.png)

**Comment by czsmall** [comment]
> 

嗯嗯  那我要怎么去做更改呢？直接更新嘛？

**Comment by czsmall** [comment]
@weekdaycare

**Comment by weekdaycare** [comment]
@czsmall 对的，更新然后参考文档 [实现「笔记」页面](https://xaoxuu.com/wiki/stellar/advanced-settings/#%E5%AE%9E%E7%8E%B0%E3%80%8C%E7%AC%94%E8%AE%B0%E3%80%8D%E9%A1%B5%E9%9D%A2)

**Comment by czsmall** [comment]
@weekdaycare 要我怎么更新？我改了下图部分。没生效
![image](https://user-images.githubusercontent.com/110958481/200204449-1820b593-6a3f-452b-8abc-97c320c35c23.png)

**Comment by weekdaycare** [comment]
`npm i`之后`hexo cl`清除缓存`hexo g`重新生成

**Comment by czsmall** [comment]
npm i  报这个有影响嘛？  完整的npm i  在hexo clean && hexo g && hexo s 。。还是没变化

**Comment by czsmall** [comment]
@weekdaycare

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200205217-0b054356-3dc6-49ba-83ee-87b5107cb56c.png)

**Comment by weekdaycare** [comment]
报这个是正常更新。你的便签页面的font-matter是按照文档编写的吗？

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200207390-cd4aa41b-e2f1-40a8-926f-f6da007d866b.png)
是这样，我不确定是否有问题，，来回更改过
还有就是，怎么确定，更新是否成功了呢

**Comment by czsmall** [comment]
@weekdaycare

**Comment by weekdaycare** [comment]
我这边测试了一下，显示正常
<details>
<summary>projects.yml</summary>

```yml
Notes:
  name: 便笺
  title: 便笺
  subtitle: 杂七杂八的收藏
  description: 
  index: false # 不在wiki列表中索引这个项目
  tags: 
```

</details>

<details>
<summary>index.md</summary>

```yml
---
menu_id: notes
layout: wiki
wiki: Notes
title: 项目
order: 0
comments: false
---
```

</details>

**Comment by czsmall** [comment]
en   找大佬替换了新报。好了
