### ISSUE TITLE
1.15.0 更新后出现了 Multiple meta description tags

### ISSUE THREAD

**Issue by i-abc** [xaoxuu/hexo-theme-stellar#168]
如图，MOZ 的分析：
![image](https://user-images.githubusercontent.com/104631897/200206008-0aaa60b7-0eff-482d-99cb-63f90ded838b.png)
![image](https://user-images.githubusercontent.com/104631897/200206036-e126af86-3e7c-47d5-808c-dddec684a7e1.png)
这是 ahrefs 的分析：
![image](https://user-images.githubusercontent.com/104631897/200206403-e351d0d4-d9b1-4460-9f69-397a9dd8e4b2.png)

**Comment by xaoxuu** [comment]
除了这个还有别的问题没

**Comment by i-abc** [comment]
> 除了这个还有别的问题没

无

**Comment by xaoxuu** [comment]
1.15.1 已修复

**Comment by i-abc** [comment]
> 除了这个还有别的问题没

突然发现 `Title` 也受到了影响，主要影响了那些非独立页面的 `Title`：
![image](https://user-images.githubusercontent.com/104631897/200317573-ae62ef9f-a74c-4fd5-8851-ec54775c7e10.png)
![image](https://user-images.githubusercontent.com/104631897/200317591-c80c6d5b-a168-420d-9d2a-02d772d700ef.png)

**Comment by xaoxuu** [comment]
你更新再看看
