### ISSUE TITLE
添0加的本站运行天数，如何同脚页融为一体。而不是下面这样

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#169]

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200311101-8fa9f707-84f4-4027-b98c-a1392b5d06cb.png)

**Comment by weekdaycare** [comment]
在footer.content里面写script就是了

**Comment by czsmall** [comment]
我就是在footer.ejs文件中添加的script 内容呀    不知道到时代码问题还是格式问题！

**Comment by weekdaycare** [comment]
`_config.stellar.yml`中的`footer`里面的`content`

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200319138-c7590039-12f5-4075-a9ac-b6ce943bb3db.png)
各种尝试 各种报错！！

**Comment by weekdaycare** [comment]
整个content用html语法写，去掉script缩进与注释，把整个script写成一行

**Comment by weekdaycare** [comment]
示例
```html
由 <a href="https://hexo.io/zh-cn/index.html">Hexo</a> & <a href="https://github.com/xaoxuu/hexo-theme-stellar">Stellar</a> 强力驱动
<span id="span"></span><script type="text/javascript">function runtime(){X = new Date("11/16/2021 23:00:00");Y = new Date();T = (Y.getTime()-X.getTime());M = 24*60*60*1000;a = T/M;A = Math.floor(a);b = (a-A)*24;B = Math.floor(b);c = (b-B)*60;C = Math.floor((b-B)*60);D = Math.floor((c-C)*60);span.innerHTML = "勉强运行"+A+"天"+B+"小时"+C+"分"+D+"秒"}setInterval(runtime, 1000);</script>
```

**Comment by czsmall** [comment]
> 示例
> ```html
> 由 <a href="https://hexo.io/zh-cn/index.html">Hexo</a> & <a href="https://github.com/xaoxuu/hexo-theme-stellar">Stellar</a> 强力驱动
> <span id="span"></span><script type="text/javascript">function runtime(){X = new Date("11/16/2021 23:00:00");Y = new Date();T = (Y.getTime()-X.getTime());M = 24*60*60*1000;a = T/M;A = Math.floor(a);b = (a-A)*24;B = Math.floor(b);c = (b-B)*60;C = Math.floor((b-B)*60);D = Math.floor((c-C)*60);span.innerHTML = "勉强运行"+A+"天"+B+"小时"+C+"分"+D+"秒"}setInterval(runtime, 1000);</script>
> ```

不报错，不显示。

**Comment by weekdaycare** [comment]
我改了下代码，再试试

**Comment by xaoxuu** [comment]
@weekdaycare 大佬你太有耐心了🌹

**Comment by czsmall** [comment]
> @weekdaycare 大佬你太有耐心了🌹

不好意思。。

**Comment by czsmall** [comment]
> 示例
> 
> ```
> <center><a href="https://hexo.io/zh-cn/index.html">Hexo</a> & <a href="https://github.com/xaoxuu/hexo-theme-stellar">Stellar</a> 强力驱动</br><span id="span"></span><script type="text/javascript">function runtime(){X = new Date("11/16/2021 23:00:00");Y = new Date();T = (Y.getTime()-X.getTime());M = 24*60*60*1000;a = T/M;A = Math.floor(a);b = (a-A)*24;B = Math.floor(b);c = (b-B)*60;C = Math.floor((b-B)*60);D = Math.floor((c-C)*60);span.innerHTML = "勉强运行"+A+"天"+B+"小时"+C+"分"+D+"秒"}setInterval(runtime, 1000);</script></center>
> ```

这代码可以的。

**Comment by czsmall** [comment]
> 我改了下代码，再试试

@weekdaycare 还有一点就是。想左边对齐的话。要怎么改呢。。百度出来的都不一样！

**Comment by weekdaycare** [comment]
去掉`<center>...</center>`就行了

**Comment by czsmall** [comment]
> 去掉`<center>...</center>`就行了

嗯 我去掉了前后的<center>  </center>`之后，对齐时对齐了。但是后面的本站运行时间有没了。。尴尬

**Comment by weekdaycare** [comment]
可以学学html基本标签，我这里有点 ~~图方便~~ （偷懒）直接用了`<center>`你去掉center可能显示会有点问题，所以把center换成div包裹起来就行了`<div>...</div>`

**Comment by czsmall** [comment]
> <div>

大功告成，有机会在了解二HTML吧。谢谢大佬！！

**Comment by skyreeves** [comment]
> 整个content用html语法写，去掉script缩进与注释，把整个script写成一行

我就说为啥我两行内容的间距很大。。把之前的MD格式改成html就好了~
