### ISSUE TITLE
在release页面发布新版本的时候希望增加版本说明

### ISSUE THREAD

**Issue by cayzlh** [xaoxuu/hexo-theme-stellar#17]
在[release](https://github.com/xaoxuu/hexo-theme-stellar/releases)页面发布新版本的时候希望增加版本说明。

有时候知道更新了，但是不知道更新了啥，而且有时候旧版的配置文件内容不能兼容最新版本（比如：`sidebar.widgets.default`改成`sidebar.widgets.default_layout`）会导致`hexo g`命令报错；

**Comment by xaoxuu** [comment]
好的，现在已经加上了： [#1.3.0](https://github.com/xaoxuu/hexo-theme-stellar/releases/tag/1.3.0)
