### ISSUE TITLE
分享链接的网址没有变为自己的网址，请问如何设置呀？

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#174]
![image](https://user-images.githubusercontent.com/68626438/201019596-856d64b9-d7bf-4fe7-9f36-a6be68361eb7.png)

```
  # 文章许可协议
  license: '本文采用[署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/)许可协议，转载请注明出处。'
  # 分享
  share:  [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5
```

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/issues/167 这里面要改成自己的：
<img width="385" alt="image" src="https://user-images.githubusercontent.com/16400144/201020518-421827e4-12f2-4163-9528-87e7bea01d5f.png">

**Comment by deskside** [comment]
谢谢！
