### ISSUE TITLE
分类和标签，显示无法获取

### ISSUE THREAD

**Issue by guyingd** [xaoxuu/hexo-theme-stellar#177]
Cannot GET /tags/
Cannot GET /categories/
![Screenshot_2022-11-14-17-46-19-058_com android chrome](https://user-images.githubusercontent.com/79262296/201628169-3a39b228-252e-4ffc-8766-b6982510370f.jpg)

**Comment by weekdaycare** [comment]
能说说做过哪些改动吗？主题默认是不需要创建tags和categories文件夹的

**Comment by guyingd** [comment]
> 能说说做过哪些改动吗？主题默认是不需要创建tags和categories文件夹的

标签和分类有显示但点击无法访问，显示Cannot GET ，奇怪的是归档又是正常的，我用的是作者仓库最新的主题

**Comment by guyingd** [comment]
> 

并没有改动，是新建的hexo，和拉取的作者仓库主题

**Comment by guyingd** [comment]
> 能说说做过哪些改动吗？主题默认是不需要创建tags和categories文件夹的

问题解决，我配置文件Directory多了个/导致的
