### ISSUE TITLE
全站tags和categories

### ISSUE THREAD

**Issue by hermitlsr** [xaoxuu/hexo-theme-stellar#18]
我发现首页的tags和categories仅对普通的文章生效，而对于layout: wiki 的文章设置tags 和 categories 是无效的，他们并不会归入首页的tag和categories中。而一个项目/笔记可能涉及多方面的内容或技术，有时通过感兴趣的tags来索引或许更方便获得某个项目中自己感兴趣的那部分。
这应该不违背wiki的理念：
>自动意味着 Stellar 可以自动找到一个项目的所有文档分页，生成一个目录树，半自动意味着您可以手动指定顺序、标题、分组，而非依赖文件路径、文件名来排序和显示。

只是多一个访问到文档的途径。

**Comment by xaoxuu** [comment]
现在已经由 `group` 改为和文章一样的 `tags` 了，数据和文章不通用，但是用法和筛选逻辑相同。

`http://localhost:4000/blog/tags/` 本就属于「博客」栏目下的，如果能筛选出另一个栏目的数据，反而不好。

如果实在想要全站生效，可以给这些库提建议，因为这部分功能不是我开发的：

- hexo-generator-category
- hexo-generator-tag
