### ISSUE TITLE
issue中能提交视频了，时间线中也能更新，但是为什么播放不了？

### ISSUE THREAD

**Issue by shaoyaoqian** [xaoxuu/hexo-theme-stellar#180]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/115222128/202833572-11e39eca-7d32-4b90-828b-5773e9c5ba32.png">
比如下面这个，能在时间线中显示，但是缺一个播放按钮🥸

<video  width = "200" src="https://user-images.githubusercontent.com/115222128/202833395-a410c8b9-dc6b-4170-99d0-4245b822f1f2.mp4"></video>

**Comment by xaoxuu** [comment]
video 标签里加上 controls 就可以啦

**Comment by shaoyaoqian** [comment]
哇塞，太棒了，朋友圈能发的，这里都能发了，耶！

**Comment by shaoyaoqian** [comment]
已经成功了
