### ISSUE TITLE
{% swiper width:max %} 放到 {% border %} 里面后不能切换照片。

### ISSUE THREAD

**Issue by shaoyaoqian** [xaoxuu/hexo-theme-stellar#181]
图片不能左右切换了
<img width="794" alt="image" src="https://user-images.githubusercontent.com/115222128/202835296-136176aa-79db-4d2c-a9be-f8e26f5548af.png">

```

{% border %}
{% image /img/logo.png width:300px padding:40px %}
{% tabs active:2 align:center %}

<!-- tab 简介 -->
这里是我的简介，然后放一些图片吧～

{% swiper width:max %}
![WechatIMG2](https://images_github.pengfeima.cn/images/202211180033899.jpeg)
![WechatIMG22](https://images_github.pengfeima.cn/images/202211180032716.jpeg)
{% endswiper %}

{% endtabs %}
{% endborder %}


```

**Comment by shaoyaoqian** [comment]
抱歉，问问题问得太快了，应该是我浏览器缓存的原因，现在没问题了。

**Comment by xaoxuu** [comment]
这个我也不知道什么情况

**Comment by shaoyaoqian** [comment]
应该是hexo-renderer-kramed的问题，我换成了hexo-renderer-markdown-it-plus已经没有这个问题了。

PS  border tabs这些命令是stellar特有的还是hexo所有主题都可以用这些命令？

**Comment by xaoxuu** [comment]
是特有的

**Comment by shaoyaoqian** [comment]
嗯嗯，目前为止，hexo-renderer-pandoc和hexo-renderer-kramed渲染这些特有命令时可能会出问题
