### ISSUE TITLE
dynamic timeline 无法正常渲染

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#185]
所有页面的动态 timeline 和小组件 widget 的 timeline 都无法显示。

- 检查了一下，用浏览器打开对应 api 网址是可以看到 api 获取到信息的，但是在博客里无法显示。
- 静态 timeline 可以正常显示。
- Stellar 版本号1.16.0
- timeline 的格式应该没有写错。

```
{% timeline api:https://api.github.com/repos/deskside/emodiary/issues %} {% endtimeline %}
```

**Comment by xaoxuu** [comment]
页面地址发一下我去看看

**Comment by deskside** [comment]
填写了如上api的[页面](https://deskside.github.io/wiki/EmoDiary/updates.html)啥也显示不了

填写了Stellar仓库issue api的[页面](https://deskside.github.io/wiki/)却能显示一条？好奇怪哈哈

**Comment by xaoxuu** [comment]
你更新一下试试好了没

**Comment by deskside** [comment]
感谢@xaoxuu 大大！你太强了！但是好像还不行诶，您的更新是指`npm i`吗？

（我看仓库里release的版本号没有升级成1.16.1，是不是无法升级到位呀）

![image](https://user-images.githubusercontent.com/68626438/203069851-af70952d-4f6c-4a61-9c9d-a74bfe89e1d5.png)

**Comment by xaoxuu** [comment]
还没发 `npm` 版本，我现在发一下

**Comment by deskside** [comment]
现在有了！太感谢了
