### ISSUE TITLE
非自定义页面的 Title 重复

### ISSUE THREAD

**Issue by i-abc** [xaoxuu/hexo-theme-stellar#186]
最新版本，非自定义页面的 Title 中的站点名称会重复。
如图：
![image](https://user-images.githubusercontent.com/104631897/203066956-f2b016eb-1cf8-4f70-b97d-d55ec8593281.png)

**Comment by xaoxuu** [comment]
再试一下呢🥹

**Comment by i-abc** [comment]
> 再试一下呢🥹

修好了！
