### ISSUE TITLE
请问 我要把我这个博客，放在自己服务器上，Centos+nginx环境，要怎么实现呢。

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#187]

**Comment by czsmall** [comment]
我要把本地那个目录文件，放到nginx的htnl目录下

**Comment by xaoxuu** [comment]
有自动化部署方案，我现在就是，但是我没有时间写教程，只有关键部分的笔记：[GitHub Action + Hexo 部署到服务器](https://xaoxuu.com/notes/server/#GitHub-Action-Hexo-%E9%83%A8%E7%BD%B2%E5%88%B0%E6%9C%8D%E5%8A%A1%E5%99%A8)
看不懂的话可以搜一搜相关教程，往上有很多的。
