### ISSUE TITLE
Waline 评论系统中的长链接溢出

### ISSUE THREAD

**Issue by i-abc** [xaoxuu/hexo-theme-stellar#189]
如果使用 Waline 评论系统，当一个链接过长，会出现溢出现象，如图：
![image](https://user-images.githubusercontent.com/104631897/203783365-d592b31b-6c1e-48df-ab1c-e673c4d8ec24.png)
此现象在电脑、手机页面皆会出现，而且在手机中影响更为严重，会影响页面大小：
![}Y4AA_DRQRPS{}J7G{_@W@F](https://user-images.githubusercontent.com/104631897/203784321-8db3cacc-4cf1-475e-b095-20e2ba55173c.jpg)
复现链接：https://www.shifeiti.com/about/
同时经在 Waline 官网测试，并未出现溢出现象；如果是使用 giscus，也不会产生这种现象。

**Comment by xaoxuu** [comment]
这个也是当时为了防止换行导致特效没覆盖加了 `keep-all`，去掉这个就好了

**Comment by i-abc** [comment]
> 这个也是当时为了防止换行导致特效没覆盖加了 `keep-all`，去掉这个就好了

好，成功解决，谢谢老大！
