### ISSUE TITLE
部署后timenode报错

### ISSUE THREAD

**Issue by lifeafter619** [xaoxuu/hexo-theme-stellar#192]
大佬，刚部署了stellar，但是hexo g报错了
![Snipaste_2022-11-30_10-52-13](https://user-images.githubusercontent.com/65111206/204696202-687adb5f-ff30-40ef-a51f-b399a7da4caf.png)
初学hexo，这怎么搞啊

**Comment by xaoxuu** [comment]
没有timenode标签，写错了吧

**Comment by lifeafter619** [comment]
啊，，那有noteblock表情嘛...

**Comment by xaoxuu** [comment]
没有，升级到6.x之后不能用这个名字了，改名了
