### ISSUE TITLE
希望能timeline能增加json等其他数据接口

### ISSUE THREAD

**Issue by shaoyaoqian** [xaoxuu/hexo-theme-stellar#194]
我的想法是，能够爬取自己的微博，将数据保存在github仓库里，然后再在博客页面中通过timeline的形式展示

**Comment by shaoyaoqian** [comment]
item.user.login                           // 用户名
        item.user.html_url                        // 主页 url
        item.user.avatar_url                      // 头像 url
        item.created_at                           // 发表日期 "2022-11-29T14:27:08Z"
        item.title || item.name || item.tag_name  // 三个中至少出现一个，item.name || item.tag_name 只有releases API会有。
        item.body                                 // 内容
        item.labels                               // 标签
        item.zipball_url                          // 选填，下载附件 releases API会有。
        item.reactions                            // 点赞数
        item.reactions.total_count                // 应该是点赞数
        item.comments                              // 评论数

**Comment by shaoyaoqian** [comment]
精简一下：
item.user.login                           // 用户名
item.user.html_url                        // 此条微博的链接
item.created_at                           // 发表日期 "2022-11-29T14:27:08Z"
item.body                                 // 内容
item.转发数                                // 转发数
item.reactions                            // 点赞数
item.comments                             // 评论数

**Comment by shaoyaoqian** [comment]
再精简一下
item.user.login                            // 用户名
item.user.html_url                      // 用户链接
item.created_at                          // 日期
item.body                                    // 内容

**Comment by xaoxuu** [comment]
人家是会反爬虫的吧

**Comment by xaoxuu** [comment]
你可以试一下直接内嵌一个 `iframe` 标签

**Comment by shaoyaoqian** [comment]
目前把爬虫弄好了：
https://github.com/shaoyaoqian/WeiboSpider/blob/output/output/user_spider_20221130152812.jsonl
我看了一下timeline代码，我照着你的改就行了，加一个args.type==weibo。细节周末再弄了。

**Comment by xaoxuu** [comment]
厉害啊👍
这么看来能在自己博客看微博动态了😄

**Comment by shaoyaoqian** [comment]
弄成这样了，只不过不知道怎么把评论点赞转发数据移动到右下角
<img width="942" alt="image" src="https://user-images.githubusercontent.com/115222128/204978505-e3639129-bd2f-4e79-ab55-89422874cfc7.png">

``` js
        // 每条微博的右下角 转发 评论 点赞
        cell += '<div class="footer">';
        cell += '<div class="flex left">';
        cell += '</div>';
        cell += '<div class="flex right">';
        cell += '<div class="item reaction repost">';
        cell += '<span>' + '转发' + ' ' + item.reposts_count + '</span>';
        cell += '</div>';
        cell += '<a class="item comments last" href="' + item.url + '#issuecomment-new" target="_blank" rel="external nofollow noopener noreferrer">';
        cell += '<span><svg t="1666270368054" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2528" width="200" height="200"><path d="M952 64H72C32.3 64 0 96.3 0 136v508c0 39.7 32.3 72 72 72h261l128 128c14 14 32.5 21.1 50.9 21.1s36.9-7 50.9-21.1l128-128h261c39.7 0 72-32.3 72-72V136c0.2-39.7-32.1-72-71.8-72zM222 462c-39.8 0-72-32.2-72-72s32.2-72 72-72 72 32.2 72 72-32.2 72-72 72z m290-7.7c-39.8 0-72-32.2-72-72s32.2-72 72-72 72 32.2 72 72c0 39.7-32.2 72-72 72z m290 8c-39.8 0-72-32.2-72-72s32.2-72 72-72 72 32.2 72 72c0 39.7-32.2 72-72 72z" p-id="2529"></path></svg> ' + (item.comments_count || 0) + '</span>';
        cell += '</a>';
        cell += '<div class="item reaction attitudes">';
        cell += '<span>' + '点赞' + ' ' + item.attitudes_count + '</span>';
        cell += '</div>';

        cell += '</div>';
        cell += '</div>';
        // 右下角结束
```

**Comment by shaoyaoqian** [comment]
方法如下：
1. fork 这个仓库 https://github.com/shaoyaoqian/WeiboSpider，修改自己的仓库名
2. 修改 .github/workflows/main.yml 中的微博ID，修改完后每天会自动更新你的微博，存储为json文件。
3. 在博客中插入timeline

{% timeline limit:100 type:weibo api:https://raw.githubusercontent.com/GitHub用户名/仓库名/output/output/tweets.json %}{% endtimeline %}

**Comment by xaoxuu** [comment]
终极版本： https://blog.thatcoder.cn/Stellar-Timeline-More/
