### ISSUE TITLE
npm i hexo-theme-stellar 后在themes文件夹下没有主题文件夹

### ISSUE THREAD

**Issue by blainehuang1028** [xaoxuu/hexo-theme-stellar#195]
npm i hexo-theme-stellar 后在themes文件夹下没有主题文件夹

**Comment by deskside** [comment]
不一定要有的，如果终端提示配置成功了，那就已经有了。你跟着[官方指南](https://xaoxuu.com/wiki/stellar/theme-settings/)操作就好了。 @CarlaRadames

**Comment by blainehuang1028** [comment]
好滴 已经解决！感谢🙏
