### ISSUE TITLE
大佬有没有兴趣弄个网易云音乐插件？

### ISSUE THREAD

**Issue by shaoyaoqian** [xaoxuu/hexo-theme-stellar#201]
如果直接用网易云提供的iframe代码，很多VIP音乐都播放不了。我自己搭建了一个网易云音乐的第三方API，你看看 https://netease.pengfeima.cn ，可以获取VIP歌曲的播放链接。你给我一VIP首歌的ID，我可以返给你这首歌的http链接。我希望以后只要在博客中插入下面这段代码就能出现播放按钮。
```
{% neteasemusic  id:5162502 %}
```

存在下面一些问题：
1. 这个服务是我自己搭建的，因此播放链接是用我的账号和密码去获取的，因此只能小范围。
2. 因为这个链接是临时链接，需要在访客浏览博客时临时获取。
3. 获取到的是http链接，不知道在https网站能不能加载，chrome系的浏览器好像不行。

看起来就不实用哈哈～

**Comment by xaoxuu** [comment]
可能要在 `2.x` 做了。
你可以试试 aplayer

**Comment by shaoyaoqian** [comment]
加了aplayer后编译报错～

**Comment by shaoyaoqian** [comment]
我还是不清楚https网站中可不可以有http链接，是不是一些浏览器不允许的，或者是我自己的问题？

**Comment by abnerwei** [comment]
> 

https站点会block掉http的资源，只能加载https的或者嵌套个iframe

**Comment by shaoyaoqian** [comment]
找到了一款音乐播放器插件，叫做 alice-player，打算放到sidebar上。
<img width="367" alt="image" src="https://user-images.githubusercontent.com/115222128/205823088-b8b8cd6c-f6e4-4546-9f5f-1b6b1e4536c4.png">
<img width="391" alt="image" src="https://user-images.githubusercontent.com/115222128/205823129-c1289328-b08f-4c9e-91d1-8cc2d6fc5986.png">
使用起来也很方便：
<img width="391" alt="image" src="https://user-images.githubusercontent.com/115222128/205823129-c1289328-b08f-4c9e-91d1-8cc2d6fc5986.png">

我真是人菜瘾大爱魔改啦啦啦啦～

**Comment by shaoyaoqian** [comment]
有了点头绪。

- [ ] 创建layout/_partial/widgets/player.ejs文件，返回`<div class="music-player" id="' + item.player + '"></div>`

**Comment by shaoyaoqian** [comment]
其次是post中的音乐播放器。这个暂时不写。

**Comment by shaoyaoqian** [comment]
最后是执行渲染的js文件。

```javascript
      var player = '#app'
      var playList = [
        { 
        audio: 'https://raw.githubusercontent.com/shaoyaoqian/images-1/main/music/Rainy%20Mood.mp3',
        cover: 'http://qiniu.pengfeima.cn/typora/202212062310206.jpg',
        name: 'Rainy Mood',
        artist: 'www.rainymood.com',
       },
        { 
        audio: 'https://raw.githubusercontent.com/shaoyaoqian/images-1/main/music/Christopher%20Larkin%20-%20The%20White%20Lady.mp3',
        cover: '/img/空洞骑士-黄蜂女.png',
        name: 'AA name',
        artist: 'AA',
      },

      ];
      var options = {
        container: player,
        preload: 'metadata',
      };
      var ap = new AlicePlayer(playList, options);
```

**Comment by shaoyaoqian** [comment]
样式文件和js文件
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/shaoyaoqian/alice-player@stable/dist/style.css" />
<script src="https://cdn.jsdelivr.net/npm/vue@next"></script>
<script src="https://cdn.jsdelivr.net/gh/shaoyaoqian/alice-player@stable/dist/alice-player.umd.js"></script>

**Comment by xaoxuu** [comment]
大佬执行力太强了 👍
这个 UI 是可以自定义的吗

**Comment by shaoyaoqian** [comment]
@xaoxuu 是可以换，可以自己写一个播放器的类，接收一个id和一个播放列表，我的也是fork别人的。学完js学vue，是有点痛苦的哈～

**Comment by xaoxuu** [comment]
有没有单个音乐播放的插件，播放列表太大了，也不太适合非pjax博客 Message ID: ***@***.***>
