### ISSUE TITLE
Artalk如何嵌入主题？

### ISSUE THREAD

**Issue by easyf12** [xaoxuu/hexo-theme-stellar#206]
想问下，Artalk如何嵌入stellar主题？目前主题也没有集成，想自己配置一下。

**Comment by xaoxuu** [comment]
我加进去了，但是我没有用过 Artalk 评论，也没有经过测试，你用下看看有没有问题。

**Comment by easyf12** [comment]
> 我加进去了，但是我没有用过 Artalk 评论，也没有经过测试，你用下看看有没有问题。

很好，感觉不错！应该可以加入正式版本了。

**Comment by easyf12** [comment]
> 我加进去了，但是我没有用过 Artalk 评论，也没有经过测试，你用下看看有没有问题。

<img width="575" alt="image" src="https://user-images.githubusercontent.com/61322612/206914055-ca07f31b-1fdb-432b-821d-457fd51e4bf5.png">
