### ISSUE TITLE
<!-- more -->会被站内搜索功能错误搜到

### ISSUE THREAD

**Issue by Vanadiry** [xaoxuu/hexo-theme-stellar#211]
在[编写文章以及独立页面/内容摘要](https://xaoxuu.com/wiki/stellar/pages/#%E5%86%85%E5%AE%B9%E6%91%98%E8%A6%81)里提到的隔开摘要和正文的`<!-- more -->`会被站内搜索功能搜到。
例如搜索“more”，会出现一堆包含`<!-- more -->`但实际文中并未出现“more”这个词的文章。

**Comment by xaoxuu** [comment]
是有这个问题，我也设置了正则删掉，但是没有效果，不知道为什么。
https://github.com/xaoxuu/hexo-theme-stellar/blob/main/scripts/generators/search.js#L52
> 以我自己的博客为例，加了这行，最终能搜到 7 条 `<!-- more -->` 而不加的话，能搜到 29 条。

**Comment by weissyu** [comment]
如果我理解他作用沒有錯誤，會不會是這段有關？

https://github.com/xaoxuu/hexo-theme-stellar/blob/main/scripts/generators/search.js#L35
我博格有兩份文章，其中一份能被搜到，它主要是沒有使用到 {% 語法。
從上面判斷式看起來確實是要帶有 {% 才會進去處理，包含 [L52](https://github.com/xaoxuu/hexo-theme-stellar/blob/main/scripts/generators/search.js#L52)。

**Comment by xaoxuu** [comment]
@weissyu L35 这个是早期加的判断条件，那时候还没有处理 `<!-- xxx -->` 这类信息，原来是这个原因，怪不得删不干净！我应该把这些放在判断条件外面才行。
