### ISSUE TITLE
站内搜索搜不到”网站卡片“里的信息

### ISSUE THREAD

**Issue by Vanadiry** [xaoxuu/hexo-theme-stellar#212]
把自己收藏的书签用网站卡片的形式放在博客里，但是发现站内搜索搜不到”[网站卡片](https://xaoxuu.com/wiki/stellar/tag-plugins/data/#sites-%E7%BD%91%E7%AB%99%E5%8D%A1%E7%89%87)“里的信息。

以为是我的配置有问题，去Stellar文档试了一下发现确实不行T^T
![截图](https://user-images.githubusercontent.com/77710715/207000067-622814a3-764f-4617-b6ec-9a206c5c83d3.png)

**Comment by xaoxuu** [comment]
目前搜索数据依据的是 `md` 文件里的源数据，没有考虑到这点，但如果换成渲染后的数据的话体积会大很多。

**Comment by xaoxuu** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/16400144/208646163-24c43030-9e43-4787-b741-9a46a518891b.png">

**Comment by xaoxuu** [comment]
体积确实会大一点，但也还能接受，我这里的是 `225KB` -> `248KB`
