### ISSUE TITLE
url的#号跳转问题

### ISSUE THREAD

**Issue by Vanadiry** [xaoxuu/hexo-theme-stellar#213]
做了一个专门放收藏的网站的页面：[magic.vanadiry.com/url/tools](https://magic.vanadiry.com/url/tools/)，发现从目录跳转到页面某一节时候会没有反应，要等到页面加载一会才能跳转到指定的地方，在页面比较长的时候要等更久，用的主题版本是1.18.0。

比如我在下面的页面里点目录里的“其它”，或者直接访问[/url/tools/#其它](https://magic.vanadiry.com/url/tools/#%E5%85%B6%E5%AE%83)的时候，要等将近半分钟才能到跳指定的位置。之前版本的主题跳转时候是正常的。

![url](https://user-images.githubusercontent.com/77710715/207255326-11c5f664-144c-47df-bba7-24976fc66e58.png)

https://user-images.githubusercontent.com/77710715/207260156-03be3de9-c73f-4f8b-861b-bc3ec3801125.mp4

然后我去看了以下您网站上类似的页面，发现直接访问[xaoxuu.com/bookmark/#技术加油站](https://xaoxuu.com/bookmark/#%E6%8A%80%E6%9C%AF%E5%8A%A0%E6%B2%B9%E7%AB%99)的时候也有类似情况出现，因为这个页面内容不多，所以等的时间也稍短些。

我放网站的那个页面是这样写的：

```markdown
### Wiki 文档
{% sites tools_wiki %}
### 图片搜索
......
```
想请教一下是哪里出了问题T.T

**Comment by Vanadiry** [comment]
刚才试了试在iOS和macOS的Safari，都是正常的，但是在win的chrome和edge要等加载。

**Comment by xaoxuu** [comment]
把 smooth-scroll 关掉试试

**Comment by Vanadiry** [comment]
> 把 smooth-scroll 关掉试试

正常了，感谢
