### ISSUE TITLE
[TODO] 是否可以考虑支持下 `不蒜子` 浏览量呢

### ISSUE THREAD

**Issue by soxft** [xaoxuu/hexo-theme-stellar#215]
是否可以考虑支持下 `不蒜子` 浏览量统计呢
官网: https://busuanzi.ibruce.info

**Comment by xaoxuu** [comment]
这个直接用 `inject` 设置就可以啦，很简单的。 [#外部文件注入](https://xaoxuu.com/wiki/stellar/advanced-settings/index.html#%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6%E6%B3%A8%E5%85%A5)

**Comment by soxft** [comment]
> 这个直接用 `inject` 设置就可以啦，很简单的。 [#外部文件注入](https://xaoxuu.com/wiki/stellar/advanced-settings/index.html#%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6%E6%B3%A8%E5%85%A5)

! 我去试试 谢谢谢谢, 但是外部注入 Js文件后, 在如何在页面或文章上方插入html标签呢, 只能修改主题文件么
