### ISSUE TITLE
侧边栏无搜索时, 出现错误

### ISSUE THREAD

**Issue by soxft** [xaoxuu/hexo-theme-stellar#217]
侧边栏无搜索时, 出现错误:
如图: 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/42080379/207747631-4a0c50e7-f222-4696-ae17-dbcc6b6fedac.png">
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/42080379/207747420-c1ccc0e5-50cf-4ad9-a1f1-caa35a6d1687.png">
[此处](https://github.com/xaoxuu/hexo-theme-stellar/blob/0a3ee07fc4e14c6de31c849d99eb74d51e3c1643/source/js/main.js#L335)
可以加一个 `try catch`?

浏览器是 Safari  16.2

**Comment by abnerwei** [comment]
`input#search-input` 元素找不到，加个 null 判断好了

**Comment by xaoxuu** [comment]
main 分支最新代码已修复
