### ISSUE TITLE
格式问题

### ISSUE THREAD

**Issue by gyl-coder** [xaoxuu/hexo-theme-stellar#22]
在文章中使用代码块时

预期效果如下

![image](https://user-images.githubusercontent.com/33021341/128591700-cf74fb9e-3b2f-410d-af6e-af6eade053db.png)

但是，实际效果如下

![image](https://user-images.githubusercontent.com/33021341/128591665-5f3770fa-5832-4442-a675-49f7c4b92c03.png)

请教一下，这是什么问题嘞？

**Comment by abnerwei** [comment]
```shell
curl xxx
```

**Comment by gyl-coder** [comment]
找到问题了

blog/_config.yml

```yml
highlight:
  enable: false
```
