### ISSUE TITLE
建议集成Pjax异步加载改善访问速度

### ISSUE THREAD

**Issue by easyf12** [xaoxuu/hexo-theme-stellar#220]

**Comment by xaoxuu** [comment]
wiki单个项目内部或许会考虑局部使用以改善目录切换体验，但是整站不会再用了，一方面速度改善不明显，另一方面整站将会有多个模块，彼此之间会有较大差异。（博客、wiki、社交等）

https://github.com/volantis-x/hexo-theme-volantis/discussions/818#discussioncomment-3851589

**Comment by easyf12** [comment]
好的。
