### ISSUE TITLE
link 标签出错

### ISSUE THREAD

**Issue by i-abc** [xaoxuu/hexo-theme-stellar#224]
我使用了一个 link 标签，如下：
```
{% link https://hub.docker.com/r/crazyq/pt_helper 小助手 desc:true %}
```
渲染出来链接出错了：
![image](https://user-images.githubusercontent.com/104631897/209074253-c5b9bf7c-1de2-4a4b-a8cb-f338e24ed163.png)
换了一个链接则正常，但图标、摘要没有：
![image](https://user-images.githubusercontent.com/104631897/209074463-7a6c89ad-d611-4456-965e-ccbfeb7f65d4.png)

**Comment by i-abc** [comment]
还有一个问题，要是链接过长，手机显示会超出范围：
![image](https://user-images.githubusercontent.com/104631897/209089440-43a4d194-aa17-4cc5-ad64-a6c8ada54712.png)

**Comment by xaoxuu** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/16400144/209455041-0f93f5c3-90b9-4f14-bf7d-2afe45c2a9c8.png">

第一个像是官方的BUG，我解析之前接收到的原始参数就是 `[object Object]` 了，我试着把 `/c/` 改成别的就好了，遇到这种链接就先不要用标签插件了，用 `[]()` 链接。

**Comment by xaoxuu** [comment]
第二个问题已经修复 a2d56b93583526aaa5e7313f7de61ef956d87106
