### ISSUE TITLE
分页列表显示异常

### ISSUE THREAD

**Issue by gaoyanliang** [xaoxuu/hexo-theme-stellar#229]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/33021341/210462102-c4284712-b136-4dbe-8dcd-e486a23d5ca0.png">

如上图所示，在当前处于第一页或者最后一页时，样式有些问题。 

请问一下该问题如何排查？

博客地址：https://yanliang.cool/

**Comment by xaoxuu** [comment]
hexo 更新到 6.3.0 Message ID: ***@***.***>
