### ISSUE TITLE
网站在移动端显示的问题。

### ISSUE THREAD

**Issue by WyattIsaac** [xaoxuu/hexo-theme-stellar#23]
非常感谢大佬的做的网页非常好看，非常喜爱
网页在电脑上看的时候非常好看，不过在切换到小屏幕的时候感觉感觉顶部的选项栏（非专业不知道如何称呼合适😂，不知道有没有什么办法可以更改一下哇。
![画板 2](https://user-images.githubusercontent.com/50106230/128795465-0e52243e-f16e-4faa-9b5c-6d70d07281f1.png)

**Comment by xaoxuu** [comment]
已经改好了，请更新到最新版看看。

**Comment by WyattIsaac** [comment]
好棒，希望大佬的项目越来越棒，越来越好。🐳
