### ISSUE TITLE
项目文章图片加载问题

### ISSUE THREAD

**Issue by WenGuiO** [xaoxuu/hexo-theme-stellar#232]
我新建了个wiki项目：javaweb， 图片放在resource/assets/目录下，具体如如：
```
#引用1
{% image /assets/wiki/JavaWeb/数据库基础/数据库管理系统.png  数据库管理系统示意图 %} 

#引用2
{% image /wwg/source/assets/wiki/JavaWeb/数据库基础/常见的数据库管理系统.png  常见数据库管理系统 %} 
```

结果文章却加载不来图片，我按照文档来的，是存在什么问题吗

**Comment by xaoxuu** [comment]
目录不对，建议看看官方文档 https://hexo.io/zh-cn/docs/asset-folders

> 最简单的方法是用外链，一般不会出错。

**Comment by Whbbit1999** [comment]
> 我新建了个wiki项目：javaweb， 图片放在resource/assets/目录下，具体如如：
> 
> ```
> #引用1
> {% image /assets/wiki/JavaWeb/数据库基础/数据库管理系统.png  数据库管理系统示意图 %} 
> 
> #引用2
> {% image /wwg/source/assets/wiki/JavaWeb/数据库基础/常见的数据库管理系统.png  常见数据库管理系统 %} 
> ```
> 
> 结果文章却加载不来图片，我按照文档来的，是存在什么问题吗

静态文件目录放在`source/assets/`下试试？
