### ISSUE TITLE
如何自定义博客右上角标签栏的设置。

### ISSUE THREAD

**Issue by Ruizhe0723** [xaoxuu/hexo-theme-stellar#233]
博客右上角的截图如下：
![image](https://user-images.githubusercontent.com/88533096/211187129-ba8b9588-9213-43e7-a7b5-818f5f1a81af.png)
想问问能否自定义这部分的内容？
另外，除了博客首页之外，如何在其他地方也增加类似的标签栏？

**Comment by Inetgeek** [comment]
同问

**Comment by xaoxuu** [comment]
1. 暂时不支持修改默认的
2. 可以增加，方法为：[#自定义主页文章检索栏](https://xaoxuu.com/wiki/stellar/advanced-settings/index.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A1%B5%E6%96%87%E7%AB%A0%E6%A3%80%E7%B4%A2%E6%A0%8F)

**Comment by xaoxuu** [comment]
文章的 `front-matter` 添加：
```yaml
post_list: true
```

**Comment by Giresharu** [comment]
> * 自定义主页文章检索栏

大佬您好，我用 **hexo new page projects** 这样新创建的 page 中加了 **post_list: true** 以及在主题设置做了如下设置：

```yaml
post-index:
  "项目": /projects
```

这样产生的 projects 页面带有面包屑，和默认的几个 page 相比看起来有点违和。
并且上方的标签栏不会提示当前也页面就是 “项目” 

这是正常的吗？

**Comment by xaoxuu** [comment]
@Giresharu 加上这个
```yaml
breadcrumb: false
seo_title: 项目
```
