### ISSUE TITLE
显示文章更新时间

### ISSUE THREAD

**Issue by tksmly** [xaoxuu/hexo-theme-stellar#234]
hexo可以按照更新时间排序,但是文章只会显示"发布于xxx天前",能否在有标题区域(Front-matter?)有updated且不等于date时显示"发布于xxx天前,更新于xxx天前"
[![pSZlX6J.png](https://s1.ax1x.com/2023/01/08/pSZlX6J.png)](https://imgse.com/i/pSZlX6J)

**Comment by tksmly** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/pull/235#issue-1524886562

**Comment by xaoxuu** [comment]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/16400144/215150081-a8475b89-a39b-487f-a286-b4d3ab75c67c.png">
这个叠层显示有的不够美观，更新于什么时候点进去看的时候知道就行了，所以可以放在文章内页显示

**Comment by tksmly** [comment]
内页并没有来自主题的显示(标题上面),我不认为每次更新在文章中加上时间是方便的

**Comment by xaoxuu** [comment]
目前是没有

**Comment by xaoxuu** [comment]
在正文页面，鼠标移动到【发布日期】时会额外显示【修改日期】
