### ISSUE TITLE
关于页面布局的建议

### ISSUE THREAD

**Issue by Inetgeek** [xaoxuu/hexo-theme-stellar#239]
博主你好，很荣幸采用您开发的优雅的hexo博客主题stellar。
因为第一次使用该博客框架及贵主题，可能下列的反馈不准确或者已经存在解决方案。
我在采用贵主题搭建博客时发现，文章很少的时候footer部分是紧贴文章目录版块的，这样的布局感觉视觉上不是很优雅，下列给出我建议的布局图：
![image](https://user-images.githubusercontent.com/42563262/212157633-7cdbbfe6-f045-4405-96fe-92b97f016e4c.png)
若已经有解决方案可以设置footer部分的位置（如固定在最下方并且整体居中），还望博主给出一些参考，感谢！

**Comment by xaoxuu** [comment]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/16400144/215145071-0ac6f478-a907-497c-b778-8711d9c6ede8.png">

我的建议是等文章不少于5篇的时候再看看是否优雅，另外，除了电脑大屏，还考虑一下小窗口、手机、iPad横屏的时候是否合适。
