### ISSUE TITLE
功能建议：关于说说功能的平替产品

### ISSUE THREAD

**Issue by Inetgeek** [xaoxuu/hexo-theme-stellar#244]
对于说说功能，若集成到github的issue的缺点是可能会被墙，且发文很麻烦。BBTalk现在已经失效，原作者现在采用的是memos。
memos是一个自由的备忘录管理软件，支持markdown解析，可以借助docker自由服务器部署或免费部署到render或fly.io。且有作者开发出APP方便发文，且BBTalk作者开发了浏览器插件来快速发文到memos上，非常之方便！！！
但缺点是该系统是单独的，有专门的json数据接口，希望stellar贡献团队能集成一下memos的相关接口。
memos官方仓库：https://github.com/usememos/memos
第三方集成参考：https://github.com/eallion/memos.top

**Comment by shaoyaoqian** [comment]
https://blog.pengfeima.cn/posts/1698/

**Comment by Inetgeek** [comment]
感谢大佬提供的服务，不过memos也有它独到的优点，要是能多一个方案就好了。目前memos集成到stellar我借鉴hugo博客驱动开发作者木木大佬的博客已经做到了，但如果能更好地支持timeline就更好了。by the way， 想问问大佬如果我要在stellar这个位置加一些自定义代码，怎么加是最好的，避免主题升级后的大量修改。
![stellar](https://user-images.githubusercontent.com/42563262/212771208-ebb054ed-06dd-47e3-ba17-bc2e812b31bc.png)

**Comment by shaoyaoqian** [comment]
那欢迎pr

**Comment by shaoyaoqian** [comment]
加一个<div class="zidingyi"></div>，然后用js填入内容

**Comment by Inetgeek** [comment]
> 加一个<div class="zidingyi"></div>，然后用js填入内容
@shaoyaoqian 是加在main.js里吗？我是在inject的地方注入标签实现的。
![image](https://user-images.githubusercontent.com/42563262/212902348-ad068724-d242-473e-abbb-54468967f91a.png)
但只有近期文章页面会展示

**Comment by shaoyaoqian** [comment]
> > 加一个`<div class="zidingyi"></div>`，然后用js填入内容
> 
> @shaoyaoqian 是加在main.js里吗？我是在inject的地方注入标签实现的。 ![image](https://user-images.githubusercontent.com/42563262/212902348-ad068724-d242-473e-abbb-54468967f91a.png) 但只有近期发布页面会展示

对的

**Comment by Inetgeek** [comment]
已集成memos说说功能，很方便。
1.集成了文章列表页顶部说说通知：
![image](https://user-images.githubusercontent.com/42563262/215012982-40f52297-1261-4a0b-a6af-04cd86179100.png)
2.集成了说说单独页面适配stellar主题（含移动端显示自适应）：
![image](https://user-images.githubusercontent.com/42563262/215013116-60954f43-1542-4ba9-8e23-0109119aa1af.png)
3.两部分功能自适应主题色（根据设备主题色自动切换）。
> 但是还没有时间整合到stellar主题里，有时间的时候整理和提交pr。

参考：[Colyn's Blog](https://blog.inetgeek.cn)

**Comment by kufx** [comment]
> 已集成memos说说功能，很方便。 1.集成了文章列表页顶部说说通知： ![image](https://user-images.githubusercontent.com/42563262/215012982-40f52297-1261-4a0b-a6af-04cd86179100.png) 2.集成了说说单独页面适配stellar主题（含自适应stellar主题配色及移动端显示自适应）： ![image](https://user-images.githubusercontent.com/42563262/215013116-60954f43-1542-4ba9-8e23-0109119aa1af.png) 3.两部分功能自适应主题色（根据设备主题色自动切换）。
> 
> > 但是还没有时间整合到stellar主题里，有时间的时候整理和提交pr。
> 
> **参考**：[Colyn's Blog](https://blog.inetgeek.cn)

期待大佬的pr,谢谢，能加上这个功能很不错

**Comment by xaoxuu** [comment]
已经做好了 https://github.com/xaoxuu/hexo-theme-stellar/commit/66d34a703d70cf0e782075850a49375e71807c8b
