### ISSUE TITLE
多语言独立配置

### ISSUE THREAD

**Issue by Cubik65536** [xaoxuu/hexo-theme-stellar#247]
是否可能可以使用 `_config.en.yml`, `_config.en.stellar.yml` 之类的文件来为不同的本地化语言进行配置，以方便快速的为不同语言进行站点配置

**Comment by xaoxuu** [comment]
目前stellar还是小众主题，有多语言需求的用户更少，这个做起来也比较麻烦，暂时没有这个计划，只会支持hexo内置的那套多语言文案。

**Comment by Cubik65536** [comment]
其实目前支持一下在不同语言模式下链接增加对应语言路径应该就能解决不少难以绕过去的问题（例如在英语模式下相对路径前都加一个 `/en`）

**Comment by xaoxuu** [comment]
那你试一下修改配置的 `root` 呢？

```yaml
root: /en/
```

**Comment by Cubik65536** [comment]
> 那你试一下修改配置的 `root` 呢？
> 
> 
> 
> ```yaml
> 
> root: /en/
> 
> ```

这样好像会影响没有额外路径的默认语言（中文），我稍后再尝试一下

**Comment by Cubik65536** [comment]
测试了一下，配置 `root` 只会让默认页面全部需要一个 `en`，实际上是让英语页面变成了 `/en/en` 并没有解决问题

**Comment by Cubik65536** [comment]
魔改了一下已有的多语言方案稍微实现了一下，暂时这么用好了
