### ISSUE TITLE
paginator在首页和尾页显示不正确

### ISSUE THREAD

**Issue by MicDZ** [xaoxuu/hexo-theme-stellar#249]
![图片](https://user-images.githubusercontent.com/34596177/215311727-91ba1a74-78e6-411b-9955-fb062da35741.png)
当位于首页或尾页时 不显示前一页和后一页的按钮

定位到在[49b89a0](https://github.com/xaoxuu/hexo-theme-stellar/commit/49b89a008c75343aedeeb68198ce579f836e9764)提交中 使用了hexo+6.3.0 [force_prev_next](https://hexo.io/zh-cn/docs/helpers#paginator)的特性。

stellar建议的版本是 Hexo: 5.4.0 ~ 6.3.0，该特性的引用或许会影响老用户的使用。

**Comment by xaoxuu** [comment]
其实就是少了个箭头，后面改下文档建议用最新版了

**Comment by xaoxuu** [comment]
已经修正了文档描述
