### ISSUE TITLE
请问每一页最下面的分页UI可否修改（回以前的）？

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#260]
你好，我个人更喜欢以前的UI，请问是否可以自定义修改？ 

![image](https://user-images.githubusercontent.com/68626438/217754079-97ec6e06-e0ec-46d2-8654-8eaabd6c39de.png)

**Comment by xaoxuu** [comment]
这个恐怕不行，实在喜欢可以自己把这部分改回原来的代码

**Comment by deskside** [comment]
好的，谢谢你！

**Comment by deskside** [comment]
- [ ]
