### ISSUE TITLE
关于使用 Front-matter 控制页面标题的问题

### ISSUE THREAD

**Issue by parasolwaddledee** [xaoxuu/hexo-theme-stellar#261]
在内置的页面中，head 的 title 和 og:title 的对应关系如下所示：
![image](https://user-images.githubusercontent.com/105424387/217768448-27ecc23d-3b66-4612-afc2-5d9dddaed5a4.png)

在自建的页面中，head 的 title 和 og:title 的对应关系如下所示：
![image](https://user-images.githubusercontent.com/105424387/217768760-e10013b2-149a-4e0a-90f8-b9372961d9c7.png)

在我自己实际的测试中，如果在 Front-matter 只使用 title，则效果和图一 wiki 页面一样；
如果在 Front-matter 只使用 seo_title，如 `seo_title: 朋友文章 - XAOXUU`，则会呈现图二 rss 页面的状态；

我使用 seo_title 的目的是为了隐藏正文的标题，请问在这种情况下如何同时满足 og:title 的值是页面实际的标题而不是站点名称？

**Comment by xaoxuu** [comment]
现在通过 `h1: ''` 来隐藏显示标题
