### ISSUE TITLE
如何添加笔记

### ISSUE THREAD

**Issue by YYYueZ** [xaoxuu/hexo-theme-stellar#267]
您好，请问笔记页面该如何添加笔记文章。我尝试了一些方法都失败了。本人缺少相关知识，麻烦您抽空解答，感激不尽！[实现笔记页面](https://xaoxuu.com/wiki/stellar/advanced-settings/#%E5%AE%9E%E7%8E%B0%E3%80%8C%E7%AC%94%E8%AE%B0%E3%80%8D%E9%A1%B5%E9%9D%A2)

**Comment by xaoxuu** [comment]
要结合着这个看 https://xaoxuu.com/wiki/stellar/wiki-settings/
会用wiki，就知道怎么用笔记了，目前笔记就是一个特殊的wiki项目。
