### ISSUE TITLE
请问如何添加代码一键复制功能

### ISSUE THREAD

**Issue by Forence1999** [xaoxuu/hexo-theme-stellar#268]

**Comment by Whbbit1999** [comment]
可以看一下探索号的分享，或者去[stellar主题添加代码块复制功能](https://www.whbbit.cn/2023/01/31/stellar%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E4%BB%A3%E7%A0%81%E5%9D%97%E5%A4%8D%E5%88%B6%E5%8A%9F%E8%83%BD/)里看一下

**Comment by Forence1999** [comment]
谢谢您！

**Comment by Whbbit1999** [comment]
😄，有用就行

**Comment by xaoxuu** [comment]
@Whbbit1999 你的文章看起来不错，可以提PR吗？复制成功时不用弹右上角的通知

**Comment by Whbbit1999** [comment]
> @Whbbit1999 你的文章看起来不错，可以提PR吗？复制成功时不用弹右上角的通知

可以

**Comment by Whbbit1999** [comment]
@xaoxuu 我要加到哪个文件/文件夹中比较好呢呢？

**Comment by xaoxuu** [comment]
最新版本已经支持
