### ISSUE TITLE
请问如何更改侧边栏的文字

### ISSUE THREAD

**Issue by billma007** [xaoxuu/hexo-theme-stellar#27]
![GqzLD.jpg](https://img.wenhairu.com/images/2021/08/23/GqzLD.jpg)
烦大神指点，谢谢！
（来自hexo）

**Comment by xaoxuu** [comment]
更新一下主题，这个位置将会显示入门指南告诉你如何修改

**Comment by billma007** [comment]
不好意思，我进行更新指令后仍然找不到该文件所在位置，烦大神指点一下文件名或者如何修改，谢谢！

**Comment by xaoxuu** [comment]
创建 `blog/source/_data/widgets.yml` 文件，此文件中填写需要自定义的侧边栏组件，例如 `welcome` 组件。

![image](https://user-images.githubusercontent.com/16400144/130468088-d1a0d7d8-78a0-49d6-9fc3-00bdc07d58ac.png)

**Comment by billma007** [comment]
非常感谢！
