### ISSUE TITLE
主题用的部分cdn好像挂掉了

### ISSUE THREAD

**Issue by Whbbit1999** [xaoxuu/hexo-theme-stellar#275]
近几天我发现用这个主题的好多网站的底部按钮区都消失了，应该是用的cdn访问不到了。而且这样导致好多网站打开速度都很慢。
![image](https://user-images.githubusercontent.com/60510247/222750573-a0463e71-b31a-40f0-8528-dcf83c98bc76.png)

**Comment by i-abc** [comment]
CDN 用的是 [gcore.jsdelivr.net](https://gcore.jsdelivr.net)。
几天前 IPV4 被墙了：
![image](https://user-images.githubusercontent.com/104631897/222865276-66d861a4-2fa6-4827-90df-66e289157ba0.png)
IPV6 幸存：
![image](https://user-images.githubusercontent.com/104631897/222865565-d0ce4b76-7450-47b5-adfb-008b9744ddcf.png)

**Comment by Whbbit1999** [comment]
哈哈，忘了还有这回事了
