### ISSUE TITLE
Block 里有一个小标签找不到配置

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#281]
图中框起来的地方，我在Docs里找不到在哪里配置🥺

<img width="739" alt="image" src="https://user-images.githubusercontent.com/68626438/227720231-d0759710-fb37-4b60-90b5-c55821cb547d.png">

**Comment by ThatCoders** [comment]
看这两张图你应该懂了

![image](https://user-images.githubusercontent.com/43780818/227949791-37daf8cc-0c2f-4d22-a7f4-8f025f112d19.png)

![image](https://user-images.githubusercontent.com/43780818/227950149-5d29fed8-dfc9-4a1e-b329-f3912a048727.png)
