### ISSUE TITLE
请问在git运行hexo generate时出现以下问题

### ISSUE THREAD

**Issue by billma007** [xaoxuu/hexo-theme-stellar#29]
![](https://i.postimg.cc/k4BMGDFV/error1.jpg)
![](https://i.postimg.cc/bJWyt83m/error2.jpg)
![](https://i.postimg.cc/wMN65Prg/error3.jpg)

根据提示的路径，错误来源于主题文件夹，请问哪里出错了，该怎么改
谢谢！

**Comment by xaoxuu** [comment]
你更新一下 `main` 分支的最新代码看看
