### ISSUE TITLE
数学公式超过屏幕会被隐藏，无法拖动

### ISSUE THREAD

**Issue by cyliu-phy** [xaoxuu/hexo-theme-stellar#300]
数学公式超过屏幕宽度无法滚动，比如 https://cyliu.cc/2022/09/04/Volume-of-n-ball/ 这篇post里的公式在手机里显示的时候，希望可以像表格和代码块一样加个 overflow:auto; 的属性

**Comment by hermitlsr** [comment]
之前有和xaoxuu说过这个问题，katex的话：
我记得当时是这么解决的
```
.md p.katex-block
  @media screen and (max-width: $device-tablet)
    overflow: scroll;
```
