### ISSUE TITLE
文档的 order怎么设定？

### ISSUE THREAD

**Issue by chxx2277** [xaoxuu/hexo-theme-stellar#31]
文件需要排序order 不知道怎么设定~

**Comment by chxx2277** [comment]
![Dingtalk_20210830144418](https://user-images.githubusercontent.com/56341240/131297774-63ddbac7-b89d-43c5-bd44-e7476ab836d9.jpg)
都是h1标签为何不显示嘞？~

**Comment by chxx2277** [comment]
![image](https://user-images.githubusercontent.com/56341240/131331142-58a14ecb-1046-4506-8bcd-d097574f08c7.png)
![image](https://user-images.githubusercontent.com/56341240/131331174-c6dc3fe0-51f2-48f7-85b5-72965f8f1cf4.png)
![image](https://user-images.githubusercontent.com/56341240/131331192-f573e2de-02e6-4896-8d05-f416ae5e186d.png)
在同一个文件夹里，为什么侧边栏显示不一样呢。不应该调用同一个的吗

**Comment by chxx2277** [comment]
能否共享一下wiki整个文件，这样也好调整和设置。

**Comment by xaoxuu** [comment]
我的网站拉到最底下看最后一句话

**Comment by chxx2277** [comment]
> 我的网站拉到最底下看最后一句话

看了呀，意思是就是带着数据wiki那快啦。自己调整有点问题。谢谢大佬。

**Comment by xaoxuu** [comment]
我全站都是开源的啊，为什么还要再重复发一遍wiki那部分的呢？
![image](https://user-images.githubusercontent.com/16400144/131435977-b5026fbd-731c-4ad7-928a-e593951ea65f.png)

**Comment by xaoxuu** [comment]
而且order如何排序也写的很清楚，**数字越小越靠前**：
![image](https://user-images.githubusercontent.com/16400144/131436338-cbc45dda-860e-4dbb-8cf2-848ba4289d82.png)

**Comment by chxx2277** [comment]
> 我全站都是开源的啊，为什么还要再重复发一遍wiki那部分的呢？
> ![image](https://user-images.githubusercontent.com/16400144/131435977-b5026fbd-731c-4ad7-928a-e593951ea65f.png)
> 
> 再给你发一下全站源码链接： https://github.com/xaoxuu/xaoxuu.github.io/ 想看哪部分随便看

谢谢大佬~
