### ISSUE TITLE
代码块在不同浏览器的显示不同

### ISSUE THREAD

**Issue by sereland** [xaoxuu/hexo-theme-stellar#314]
发现代码块在不同浏览器上的显示不同
- Microsoft Edge 版本 115.0.1901.203 (正式版本) (64 位)
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/130645584/0662f902-cbc2-4379-bba2-ee4841be998e)
- Firefox 版本116.0.3 (64 位)
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/130645584/76c427ec-615b-42a4-9efe-7ce24214fe52)
可以看到在Firefox上代码块的底色不一样，而且位置也有区别。请问这个是bug吗，还是feature呢？

**Comment by xaoxuu** [comment]
是因为用到了一个Firefox暂时不兼容的语法，Safari和Chrome（包括所有基于Chromium内核的浏览器）都是兼容的。
