### ISSUE TITLE
关于友链换行的问题

### ISSUE THREAD

**Issue by mjsdnz** [xaoxuu/hexo-theme-stellar#319]
为什么友链后面会自动换横？
```md
---
menu_id: more
title: 友链：
date: 2023-08-30 16:55:06
---

{% friends 我自己 %} aaa
```

![图片](https://img1.imgtp.com/2023/08/30/AOMsRwsK.png)

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/issues/312#event-10095007753

**Comment by mjsdnz** [comment]
抱歉没有看到以前的issues，谢谢
