### ISSUE TITLE
样式错位

### ISSUE THREAD

**Issue by wjsw3369** [xaoxuu/hexo-theme-stellar#320]
也是在github上看到可以在\>后面添加\#\#来变成标题，但在博客上鼠标悬停井号会错位，上面也会有一部分空白
```

> ## 123456
>
> 例：
>
> > 
> > <br>
> > 
```
如图左侧浏览器右侧Typora源代码模式
![左侧浏览器右侧md编辑器](https://github.com/xaoxuu/hexo-theme-stellar/assets/138080354/38919452-7e0c-41db-a023-7f5a4ca4ae04)
此样式在GitHub中*此处*是显示正常的，如下

> ## 123456
>
> 例：
>
> > 
> > <br>
> >

**Comment by xaoxuu** [comment]
目前没有兼容这种场景，后续会处理一下。

**Comment by wjsw3369** [comment]
在1.20.0中已经正常显示了
