### ISSUE TITLE
图片懒加载能否显示一个转圈图片

### ISSUE THREAD

**Issue by Achuan-2** [xaoxuu/hexo-theme-stellar#321]
目前图片懒加载未完全加载的图片只是空行，无法分辨是否有图片

**Comment by xaoxuu** [comment]
以前是支持的，但是因为有高度跳变，维护两套，就砍掉了这个功能，你可以翻翻历史记录看看。

**Comment by xaoxuu** [comment]
看到有大佬可以实现不会高度跳变的占位图：https://xingpingcn.top/%E4%B8%BAhexo%E5%8D%9A%E5%AE%A2%E6%B7%BB%E5%8A%A0%E8%87%AA%E9%80%82%E5%BA%94%E5%9B%BE%E7%89%87%E5%8D%A0%E4%BD%8D%E5%9B%BE.html

**Comment by Achuan-2** [comment]
那大佬能不能改进下

**Comment by Achuan-2** [comment]
好吧，我突然发现图片懒加载体验不好，关掉反而浏览体验更好
