### ISSUE TITLE
能否在博客主页侧边栏显示近期评论

### ISSUE THREAD

**Issue by Achuan-2** [xaoxuu/hexo-theme-stellar#322]
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/60436214/2371d9b3-c44a-4b4c-8ce3-3bc94d7b9433)

**Comment by ThatCoders** [comment]
每个评论插件都不同，你可以自定义一个侧边栏组件，调用自己评论插件的api即可

**Comment by Achuan-2** [comment]
> 每个评论插件都不同，你可以自定义一个侧边栏组件，调用自己评论插件的api即可

貌似 giscus 没有近期评论api

**Comment by ThatCoders** [comment]
> > 每个评论插件都不同，你可以自定义一个侧边栏组件，调用自己评论插件的api即可
> 
> 貌似 giscus 没有近期评论api

中秋没带电脑，Gsicus应该是利用GitHub Discussions，去你的discuss设置成按时间排序，用浏览器开发者工具抓一下排序后的GitHub的官方api就行

**Comment by xaoxuu** [comment]
只要有数据就好办，用timeline组件来显示，beaudar我之前就用过，别的不太清楚。

**Comment by xaoxuu** [comment]
https://blog.thatcoder.cn 这位大佬有改造过的万能时间线，应该能直接用

**Comment by lei-cau** [comment]
谢谢 大佬
