### ISSUE TITLE
自带的issues说说时间线，顺序是倒叙。怎么改为最新发布？

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#323]
最新的说说在最下面
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/110958481/d71ba0d7-1014-4ea5-b2ef-7a591afc648d)
怎么调整呢

**Comment by xaoxuu** [comment]
标签只是负责展示，具体看数据从哪来，如果是GitHub的API，可以看这里：https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-issues-assigned-to-the-authenticated-user

**Comment by czsmall** [comment]
好的
