### ISSUE TITLE
代码块中的markdown图片源码被转换成图片标签

### ISSUE THREAD

**Issue by gsh1209** [xaoxuu/hexo-theme-stellar#325]
代码块中的markdown图片源码被转换成图片标签格式

- 文本编辑器中的markdown源代码
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/113790912/e922ce89-1374-4a40-bfdb-26b81bc4a8d9)

- 生成后页面显示效果
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/113790912/64256490-d034-4fc5-986e-5d9a3fdd27d3)

可能相关的pull/commits:
- https://github.com/xaoxuu/hexo-theme-stellar/pull/252#issue-1562378422
- https://github.com/xaoxuu/hexo-theme-stellar/commit/372a382bb05f0d69b46fbe0055c922d7bc2f5011

**Comment by gsh1209** [comment]
此外，还发现如果图片文件名中包含括号，如：
```md
![XX结构图](https://img.abc.xyz/imgs/ABC(def)结构图.jpg)
```
change_image 函数中的替换规则不匹配，反而不会转换成图片标签，保留原始的markdown代码

**Comment by xaoxuu** [comment]
这问题不太好处理，建议关掉自动替换功能

**Comment by gsh1209** [comment]
好的谢谢，暂时关掉了这个功能

**Comment by xaoxuu** [comment]
因为替换的时候不知道某个图片是不是被包含在代码块中的
