### ISSUE TITLE
换行的链接鼠标放置上面的效果错位

### ISSUE THREAD

**Issue by wjsw3369** [xaoxuu/hexo-theme-stellar#328]
自动换行的链接鼠标放置上面的效果错位，如图
![657ba2496597b](https://github.com/xaoxuu/hexo-theme-stellar/assets/138080354/98a2816a-119a-4d0b-a13e-c8da1033072d)

**Comment by wjsw3369** [comment]
Microsoft Edge
版本 120.0.2210.61 (正式版本) beta (64 位)


$ hexo -v
INFO  Validating config
(node:118944) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\1111\Downloads\blog\node_modules\jsftp\package.json' of './jsftp.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
INFO  Welcome to Stellar 1.20.0
DOCS  https://xaoxuu.com/wiki/stellar/
REPO  https://github.com/xaoxuu/hexo-theme-stellar.git

hexo: 6.3.0
hexo-cli: 4.3.1
os: win32 10.0.22631
node: 18.12.0
v8: 10.2.154.15-node.12
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.10
openssl: 3.0.5+quic
cldr: 41.0
icu: 71.1
tz: 2022b
unicode: 14.0
ngtcp2: 0.8.1
nghttp3: 0.7.0

**Comment by xaoxuu** [comment]
这个是已知问题，前面的issue有，不知道怎么处理。
另外，链接不宜过长

**Comment by wjsw3369** [comment]
> 这个是已知问题，前面的issue有，不知道怎么处理。 另外，链接不宜过长

哦，好的影响不是很大
