### ISSUE TITLE
Wiki 的 Logo 选项总是显示默认值，自定义配置无法生效

### ISSUE THREAD

**Issue by parasolwaddledee** [xaoxuu/hexo-theme-stellar#335]
Wiki 的 Logo 选项总是显示默认值，即主题配置文件中 default > project 的值，Wiki YML 配置文件中指定的 Logo 配置无法生效。

主题版本：v1.21.0
仓库地址：https://github.com/parasolwaddledee/test
预览地址：https://test-rho-nine-75.vercel.app/

**Comment by xaoxuu** [comment]
- 原logo结构已废弃
- 列表图标字段改名为icon（现在是正方形框架），直接传链接
- 原cover结构改名为coverpage
- 新cover为封面图片链接（和文章的cover一致）

**Comment by parasolwaddledee** [comment]
明白了🫡
```diff
+ icon: /assets/wiki/stellar/icon.svg
- logo:
-   src: /assets/wiki/stellar/icon.svg
-   small: 108px
-   large: 180px
```
