### ISSUE TITLE
文档页不显示自定义logo

### ISSUE THREAD

**Issue by Chenli-L** [xaoxuu/hexo-theme-stellar#336]
大佬可以帮忙看看吗，我的文档页面不显示log噢，是采用图床链接形式的和旧版本一致，旧版本是正常显示的，但新版不行。
https://www.chenliss.cn/wiki

**Comment by parasolwaddledee** [comment]
logo 在新版本改成了 icon，应该是官方文档还没来得及更新：
https://github.com/xaoxuu/hexo-theme-stellar/issues/335

**Comment by Chenli-L** [comment]
明白了，谢谢
