### ISSUE TITLE
使用memos作为侧边栏经常出现不显示现象

### ISSUE THREAD

**Issue by zbzzh** [xaoxuu/hexo-theme-stellar#338]
版本：1.21.0
在多个博客均出现此现象，在无痕模式下测试，快速刷新很容易复现，怀疑是跟渲染顺序有关，而博客加载缓慢则不容易出现，测试memos api并无并发限制，换成你的memos同样会出现，控制台无报错
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/87306816/521ef9b6-0c7f-4d67-bfc1-8179343952b1)
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/87306816/f81882c6-c094-4940-9b29-a79e649d9504)
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/87306816/39bea8ce-21e2-4340-8a10-364df8e9256b)

**Comment by xaoxuu** [comment]
应该是先于其依赖的 marked 加载出来了，奇怪的是用到 marked 时未定义为什么没报错。

**Comment by zbzzh** [comment]
请求作者大大修复，我经常加载不出来 /哭笑

**Comment by xaoxuu** [comment]
https://xaoxuu.com/blog/archives/ 你看看我这里现在还能复现出来不能了

**Comment by zbzzh** [comment]
> https://xaoxuu.com/blog/archives/ 你看看我这里现在还能复现出来不能了

此页面测试已修复

**Comment by xaoxuu** [comment]
那你更新一下代码就好了

**Comment by zbzzh** [comment]
ok

**Comment by zbzzh** [comment]
你好，能否将动态设置成后加载的模式，现在主页的加载速度受限于memos，大幅降低了静态博客速度，之前是没事的

**Comment by xaoxuu** [comment]
一直是 defer 模式的呀

**Comment by xaoxuu** [comment]
<img width="1211" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/e331b9d0-a20a-49e4-a09a-45fb099c5e64">

低速3G测试，在 memos.js 没开始加载之前，页面框架和样式就已经加载好了。

**Comment by zbzzh** [comment]
嗯嗯 我的意思是浏览器的加载进度条要随着memos全部加载完才完毕，我测试没有memos的页面只需150ms加载完，而加了memos的页面则须更长时间。能否调成除了memos其余元素加载完浏览器的加载条就完事，然后让memos的页面再慢慢加载
