### ISSUE TITLE
关于电脑网页切入

### ISSUE THREAD

**Issue by Less-star** [xaoxuu/hexo-theme-stellar#34]
我是GitHub储存vercel/netlify托管
电脑端访问有一瞬手机UI。是什么情况呢
错误图   https://cdn.jsdelivr.net/gh/muzishaoxing/Picture@main/shaoxing/20210912/12:37-48nZqg.png

我的网站是  https://shaoxing.vercel.app/           https://shaoxing.netlify.app/

下面内容 不知道有没有用。贴下来做参考
    "hexo": "^5.0.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-blog-encrypt": "^3.1.6",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-indexed": "^1.2.1",
    "hexo-generator-tag": "^1.0.0",
    "hexo-hey": "^0.4.1",
    "hexo-related-popular-posts": "^5.0.1",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-tag-dplayer": "^0.3.3",
    "hexo-theme-stellar": "^1.1.0",
    "hexo-util": "^2.5.0"

**Comment by Less-star** [comment]
> 我是GitHub储存vercel/netlify托管
> 电脑端访问有一瞬手机UI。是什么情况呢
> 错误图 https://cdn.jsdelivr.net/gh/muzishaoxing/Picture@main/shaoxing/20210912/12:37-48nZqg.png
> 
> 我的网站是 https://shaoxing.vercel.app/ 
https://shaoxing.netlify.app/
> 
> 下面内容 不知道有没有用。贴下来做参考
> "hexo": "^5.0.0",
> "hexo-abbrlink": "^2.2.1",
> "hexo-blog-encrypt": "^3.1.6",
> "hexo-deployer-git": "^3.0.0",
> "hexo-generator-archive": "^1.0.0",
> "hexo-generator-category": "^1.0.0",
> "hexo-generator-feed": "^3.0.0",
> "hexo-generator-indexed": "^1.2.1",
> "hexo-generator-tag": "^1.0.0",
> "hexo-hey": "^0.4.1",
> "hexo-related-popular-posts": "^5.0.1",
> "hexo-renderer-ejs": "^1.0.0",
> "hexo-renderer-marked": "^4.0.0",
> "hexo-renderer-stylus": "^2.0.0",
> "hexo-server": "^2.0.0",
> "hexo-tag-dplayer": "^0.3.3",
> "hexo-theme-stellar": "^1.1.0",
> "hexo-util": "^2.5.0"

**Comment by xaoxuu** [comment]
你对比一下我的源码，把多余的插件和js卸载掉看看。

**Comment by MuziShaoxing** [comment]
好的我试试
