### ISSUE TITLE
更新1.22.0后Gallery图库引用无效，文章中不显示，轮播图都是正常的！

### ISSUE THREAD

**Issue by iLincc** [xaoxuu/hexo-theme-stellar#340]

**Comment by xaoxuu** [comment]
你看下我这个显示吗？

https://xaoxuu.com/blog/20231223/

**Comment by iLincc** [comment]
我看您的是正常的，但是无论我怎么调用都没有效果，代码甚至我直接都用的您的未修改进行测试，也没有任何报错，仅仅就是不显示。



---原始邮件---
发件人: "Mr. ***@***.***&gt;
发送时间: 2023年12月30日(周六) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xaoxuu/hexo-theme-stellar] 更新1.22.0后Gallery图库引用无效，文章中不显示，轮播图都是正常的！ (Issue #340)




 
你看下我这个显示吗？
 
https://xaoxuu.com/blog/20231223/

**Comment by xaoxuu** [comment]
你看下#332的评论看是不是同一个问题

**Comment by iLincc** [comment]
332有报错，可是我的没有一个报错，部署全部都是正常的，也不是缓存问题，没有报函数名调用错说明函数没有问题的，但是就是不显示，我是用的一个单页创建的index.md写在里面的。



---原始邮件---
发件人: "Mr. ***@***.***&gt;
发送时间: 2023年12月30日(周六) 晚上7:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xaoxuu/hexo-theme-stellar] 更新1.22.0后Gallery图库引用无效，文章中不显示，轮播图都是正常的！ (Issue #340)




 
你看下#332的评论看是不是同一个问题

**Comment by xaoxuu** [comment]
你继续往下看评论，后面还有个问题

**Comment by iLincc** [comment]
确实是parse_markdown的问题，关闭之后就可以了，万分感谢大佬百忙之中抽出时间解决问题!



---原始邮件---
发件人: "Mr. ***@***.***&gt;
发送时间: 2023年12月30日(周六) 晚上7:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xaoxuu/hexo-theme-stellar] 更新1.22.0后Gallery图库引用无效，文章中不显示，轮播图都是正常的！ (Issue #340)




 
你继续往下看评论，后面还有个问题

**Comment by xaoxuu** [comment]
最新版已经修复了，移除了 `parse_markdown` 功能。

**Comment by Achuan-2** [comment]
才发现parse_markdown 功能被删掉了，对纯Markdown用户就不友好了哦，能否默认是关闭，需要自己开启呢。
