### ISSUE TITLE
更新后出现2个bug，tag和启动问题。辛苦查看！

### ISSUE THREAD

**Issue by Sumorio** [xaoxuu/hexo-theme-stellar#342]
小白一枚，更新后修改过程中出现2个问题，请教大佬。
1.启动hexo s的时候显示如图的报错，是为何。
2.tag标签出现历史遗留标签，或者根本不存在的标签。
请拨冗辛苦查看，谢谢~
1.tag问题
![Snipaste_2024-01-04_12-10-29](https://github.com/xaoxuu/hexo-theme-stellar/assets/95837074/5921c75f-63dd-4483-a88b-2e026a8898dc)
![Snipaste_2024-01-04_12-09-31](https://github.com/xaoxuu/hexo-theme-stellar/assets/95837074/117025c1-d615-41f8-99f7-c76615c58469)
2.启动问题
![2024-01-04T12_08_08](https://github.com/xaoxuu/hexo-theme-stellar/assets/95837074/ea641698-e9cc-466a-9c21-b329cc1e8249)

**Comment by xaoxuu** [comment]
clean一下

**Comment by xaoxuu** [comment]
jsftp是啥

**Comment by Sumorio** [comment]
直接使用heck  Clean没有用 请问有其他原因吗

在 2024年1月4日星期四，Mr. X ***@***.***> 写道：

**Comment by xaoxuu** [comment]
```
hexo clean
```

**Comment by Sumorio** [comment]
不好意思 我打错了 的确是hexo c了，没有用的。看来您也不知道为何，我自己看看吧。谢谢了

**Comment by xaoxuu** [comment]
是的，我也不知道怎么回事，感觉就是缓存影响的
