### ISSUE TITLE
自定页面能否自定面包屑导航？

### ISSUE THREAD

**Issue by Vanadiry** [xaoxuu/hexo-theme-stellar#344]
我加了一些独立的页面，它们左上角显示“主页/xxxx”，能否给这些页面创建分类，让他们显示成“主页/分类/xxxx”
![1](https://github.com/xaoxuu/hexo-theme-stellar/assets/77710715/b9c33696-3986-4db3-a98e-eba62a5726b3)

**Comment by xaoxuu** [comment]
暂时不支持自定义
