### ISSUE TITLE
新版本Stellar Theme 友链文字显示不全，但旧版本显示正常

### ISSUE THREAD

**Issue by MSCMDD** [xaoxuu/hexo-theme-stellar#346]
新版本Stellar Theme 友链文字显示不全，但旧版本显示正常
例如：
`友情链接名字很长`

旧版本友链：
```
友情链接
名字很长
```
会自动折叠

新版本友链：

`友情链...`

**Comment by MSCMDD** [comment]
经过调试
控制台中删去white-space: nowrap;后正常
位置在main.css

**Comment by xaoxuu** [comment]
不想让它有多少显示多少，这会让自己的网站观感和交互体验变差。
另外，不至于4个字都显示不全吧，你是不是把字体设置的很大？

**Comment by xaoxuu** [comment]
我看了我的友链，7个字的都能显示完整啊

**Comment by MSCMDD** [comment]
这里建议
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/128666602/9a8e04ec-e5aa-4c8e-aeec-e5e5effd2deb)

**Comment by MSCMDD** [comment]
然后就成这样了
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/128666602/89ca1e85-9499-4f51-9186-57f5502c373b)

**Comment by MSCMDD** [comment]
emmm
但是我全新hexo init了一个博客
还是如此
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/128666602/345c3457-7255-43ed-bae3-a3ace8098d88)
或者说是浏览器的问题，可能是如此吧
，上面的是Edge
然后是Firefox
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/128666602/90bfca0b-cbab-470b-a06a-70c511e0eff2)
之后是
Chrome
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/128666602/cbbb99b6-a2ab-4919-b6e0-d03265ca0825)

**Comment by MSCMDD** [comment]
这里没有配置任何字体，完全是未经改动的环境
你提供的实例七个字。。。
在这里有问题QAQ
还是省略的
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/128666602/f34fdd5b-e7ce-4f99-aaad-6c6b871ee7d2)
Chrome
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/128666602/6b90d902-7aa8-4cb2-9e3c-4efafcd39e94)
Edge
Firefox是完整的七个字

**Comment by xaoxuu** [comment]
看来windows上情况比较复杂，我再优化一下吧

**Comment by MSCMDD** [comment]
可以了
AwA
