### ISSUE TITLE
新功能video标签 不支持bilibili

### ISSUE THREAD

**Issue by ma-wenqian** [xaoxuu/hexo-theme-stellar#348]
刚刚发现博主更新了主题版本，有了video标签，但我刚刚试了加入哔哩哔哩视频标签无法查看视频。

请问近期是否有更新计划？

**Comment by xaoxuu** [comment]
好的，我研究一下

**Comment by xaoxuu** [comment]
已经适配好了，在视频播放页地址栏上这部分复制下来就可以：

<img width="349" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/467d04bb-50ce-422e-8c0b-19ef7e780ac2">


```
{% video bilibili:BV1GP4y1d729 %}
```

**Comment by ma-wenqian** [comment]
是不是没有发布新的版本号呀，我现在还是不能正常显示

**Comment by xaoxuu** [comment]
刚刚发布了 1.24.1

**Comment by ma-wenqian** [comment]
太棒啦！
