### ISSUE TITLE
Sidebar widgets中welcome一直显示

### ISSUE THREAD

**Issue by wangjun-kk** [xaoxuu/hexo-theme-stellar#35]
.config.stellar.yml设置default_layout: [recent]，welcome还是会默认显示出来，虽然平时可以修改源码解决，但是搞站点托管，自动部署的时候问题还是会显现。

**Comment by abnerwei** [comment]
在 `_data` 文件夹中创建 `widgets.yaml` 定义组件

**Comment by xaoxuu** [comment]
截个图看一下你的welcome组件显示的内容

**Comment by wangjun-kk** [comment]
> 截个图看一下你的welcome组件显示的内容

![image](https://user-images.githubusercontent.com/45030167/133366628-765e7ea8-66f8-44c3-9a8a-234d75149b6e.png)

**Comment by wangjun-kk** [comment]
> 在 `_data` 文件夹中创建 `widgets.yaml` 定义组件

可以解决，谢谢
