### ISSUE TITLE
从1.23版本后发布时间显示有问题

### ISSUE THREAD

**Issue by zbzzh** [xaoxuu/hexo-theme-stellar#350]
默认状态不显示
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/87306816/9c7246b5-4a38-45db-9a37-538d437e2d75)
hover后才显示，但中间有明显间隔
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/87306816/3683fc09-debc-499c-bd29-a63512fe0418)

**Comment by parasolwaddledee** [comment]
这个是 1.20.0 版本的新特性：`文章：鼠标移动到发布时间时，会额外显示更新时间`
https://github.com/xaoxuu/hexo-theme-stellar/releases/tag/1.20.0

**Comment by zbzzh** [comment]
> 这个是 1.20.0 版本的新特性：`文章：鼠标移动到发布时间时，会额外显示更新时间` https://github.com/xaoxuu/hexo-theme-stellar/releases/tag/1.20.0
不是，默认的话连发布时间都不显示，触碰才会全部显示出来，而且显示间隔过大

**Comment by xaoxuu** [comment]
我看其他人那里显示都是正常的。我根据已有的信息只能得出以下建议：

1. https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
2. 再更新一下版本到 1.24.0 或者 main
3. 浏览器强制刷新一下

**Comment by xaoxuu** [comment]
<img width="424" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/96e31a84-7c81-405c-9c89-aaa837b88216">

找到原因了，你应该是自己改过css，合并代码的时候保留了部分旧版的样式：

3b300104aff266da1b8818b23f5b4465b5079c9b

<img width="293" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/26e48b2b-9c94-414c-8e35-ab8d8bc34183">

<br>

**解决办法**：重新fork主题代码

**Comment by zbzzh** [comment]
请问是哪个css文件呢，我这边已经更新到新版本了试过好多次了

**Comment by xaoxuu** [comment]
你搜索 span+span 看看

**Comment by zbzzh** [comment]
确实是hidden，但我主题都是最新的啊

**Comment by zbzzh** [comment]
[web_20240115124100.tar.gz](https://github.com/xaoxuu/hexo-theme-stellar/files/13934895/web_20240115124100.tar.gz)

**Comment by zbzzh** [comment]
这是博客所有的文件，麻烦你帮我看一下

**Comment by xaoxuu** [comment]
你发的这个是正常的

**Comment by xaoxuu** [comment]
你用 `npm i hexo-theme-stellar` 来安装吧，别改主题源码

**Comment by zbzzh** [comment]
我没有改主题源码啊，我现在就是绑定的public目录，显示还是有问题

**Comment by xaoxuu** [comment]
1. 把 themes 文件夹删掉
2. 执行 `npm i hexo-theme-stellar` 
3. 执行 `hexo clean`
4. 执行 `hexo s`

**Comment by zbzzh** [comment]
是已经部署上去了的，我又重新发布了一遍还是不行
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/87306816/b7dc01aa-6fa0-4670-b791-2338fd2dc773)

**Comment by zbzzh** [comment]
看了一下可以了，顺便问下2.0什么时候发布呢

**Comment by xaoxuu** [comment]
最后是怎么好了的？

**Comment by xaoxuu** [comment]
Stellar 2.0 还很遥远，至少要等 Volantis 6.0 发布之后才开始动工。

**Comment by zbzzh** [comment]
具体我也忘了是怎么弄好的了，我把所有文件全删了又重新部署的，中间试了一下就好了

**Comment by zbzzh** [comment]
已找到原因，cdn开启了这个功能
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/87306816/9711ae7a-4cda-4a15-a4c5-93a1578ec54c)

**Comment by xaoxuu** [comment]
🥹
