### ISSUE TITLE
主题配置里 okr 标签的 border 选项无效

### ISSUE THREAD

**Issue by parasolwaddledee** [xaoxuu/hexo-theme-stellar#357]
疑似是 css 问题：

![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/105424387/354943df-2d51-4433-aa1d-d160c8cae590)

**Comment by xaoxuu** [comment]
截图里两行一模一样的，第二行把第一行覆盖了，所以是生效的，重复了而已。

**Comment by xaoxuu** [comment]
<img width="530" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/31b984a1-ff61-4bba-9b25-56d2c4056ca9">

确实是重复了，这个开关关不掉。
