### ISSUE TITLE
使用1.23.0版本以前的links

### ISSUE THREAD

**Issue by wjsw3369** [xaoxuu/hexo-theme-stellar#358]
要怎么更改可以想之前一样，将所有的links都写在_data/links.yml中，而不是像现在这样的在_data/links/xxx.yml，我的内容比较多，如果这样迁移太麻烦了，而且之前的一些组的id有符号也是不能设置成文件名的，所有有没有什么方式可以在1.25.0中还用之前的方式来保存

**Comment by xaoxuu** [comment]
id又不会显示出来，为什么一定要设置成符号

**Comment by wjsw3369** [comment]
之前整的比较多，基本都是直接复制需要的名了，这要整出来还需要给每个文章都改改他们的id，我看了1.22.1到1.23.0之间的变更记录，我是看不太懂

**Comment by wjsw3369** [comment]
算了，不用了，用脚本给分出来了，把符号给换成下划线，又给文章中一个个改了
