### ISSUE TITLE
作者您好，感谢您的分享，想咨询一下侧边栏的问题，如下

### ISSUE THREAD

**Issue by jfdream** [xaoxuu/hexo-theme-stellar#359]
请问一下侧边栏如何做到像您官网的样子，支持点击一篇博文标题展开文章的子标题而不是默认跳转页面呢，谢谢

<img width="278" alt="截屏2024-01-17 15 52 06" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/8189379/d6b7d286-8124-486a-a3fa-1c3c6a0379f3">

**Comment by xaoxuu** [comment]
这个框里面的本文内的目录，框外的就要跳转了。

**Comment by jfdream** [comment]
您网站上的例子可以满足需求，是单独定制的功能吗

**Comment by jfdream** [comment]
感谢，大致明白了，我参考您 docs 再试试

**Comment by xaoxuu** [comment]
还在开发中，没发布版本，等 1.26.0 版本发布后就可以使用了。
