### ISSUE TITLE
大图片不能放大看 能否引入FancyBox

### ISSUE THREAD

**Issue by chxx2277** [xaoxuu/hexo-theme-stellar#36]
有些图片内容比较多 看不清

**Comment by strongduanmu** [comment]
@xaoxuu +1，现在看图片确实不方便，希望能支持下

**Comment by xaoxuu** [comment]
图片放大功能已支持：
https://xaoxuu.com/wiki/stellar/tag-plugins/#%E6%94%AF%E6%8C%81-Fancybox-%E6%8F%92%E4%BB%B6%E7%82%B9%E5%87%BB%E6%94%BE%E5%A4%A7
