### ISSUE TITLE
文章页面以 author id 判断作者，而作者资料页则以 author.name 判断作者

### ISSUE THREAD

**Issue by ericclose** [xaoxuu/hexo-theme-stellar#368]
详情见 #367 

* [文章页面以 author id 判断作者，而作者资料页则以 author.name 判断作者](https://github.com/xaoxuu/hexo-theme-stellar/issues/367#issuecomment-1903367757)

**Comment by xaoxuu** [comment]
更新一下 main 分支看看好了没

**Comment by xaoxuu** [comment]
没解决就还用 #367 那个 issue 讨论吧
