### ISSUE TITLE
佬，您的网站证书过期进不去了

### ISSUE THREAD

**Issue by Sumorio** [xaoxuu/hexo-theme-stellar#369]
如题。进不去了。
![img](https://cdn.jsdelivr.net/gh/Sumorio/BlogPic/20240123110528.png)

**Comment by Sumorio** [comment]
清楚下缓存，更改了谷歌安全等级，高级选项有继续进入选项了，开心。

**Comment by xaoxuu** [comment]
中午那会服务器重装从宝塔切换到1panel了
