### ISSUE TITLE
很抱歉！前面的问题原以为解决了，中断之后，重新启动后问题再现

### ISSUE THREAD

**Issue by johnbao6** [xaoxuu/hexo-theme-stellar#372]
重装主题 stellar 后，似乎一切正常了。

但是 用 Ctrl-C 中断后，再次启动似乎问题又再现了。 难道我要重装系统 hexo，而不仅仅是主题？

但是主题改回 landscape，似乎还是正常的。

**Comment by xaoxuu** [comment]
在上次成功之后有做过什么操作吗？

**Comment by xaoxuu** [comment]
不行的话你换一种方式来使用，先把主题源码下载下来，解压到 `/home/bao/Desktop/openctex/themes/stellar` 位置来使用，顺便把 `package.json` 中的 `hexo-theme-landscape` 和 `hexo-theme-stellar` 都删除掉，然后执行 `npm i`

**Comment by johnbao6** [comment]
我使用的是最新版的 Manjaro linux，试着重装 hexo，把原来的博客hexo 尽可能删除干净（但是不保证彻底删除）。

然后重新安装Hexo，以及 stellar。并且没有添加新的博客。

但是问题依旧。

第一次启动 Hexo server，正常。
只要 Ctrl-C，再次 启动 hexo server. 问题就出现了。

回到主题 lanscape，一起都正常了。
问题是： 不能用 Ctrl-C 中断。

**Comment by xaoxuu** [comment]
不知道什么原因，主题的源文件被替换掉了，所以无法正常启动，建议换一种方式来用，像我这样：
<img width="596" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/c892ba43-1c7a-437f-a0b0-98ab56efda98">

**Comment by johnbao6** [comment]
似乎还是有类似的问题。

我已经按照你的图放置了相关的文件。
并且把 openctex 下的 package.json 文件的 hexo-theme-landscape 一行删去，以及上一行最后的逗号也删去，但是没有你说的 hexo-theme-stellar 。
同时修改了这个目录下的 _config.yml 中 theme: stellar  （我不确信这一步是否必要）
然后执行 npm i，然后再运行 hexo server。

浏览器 http://localhost:4000/ ，没有反馈。后台的错误是：

![截图_2024-01-25_23-07-18](https://github.com/xaoxuu/hexo-theme-stellar/assets/24749194/5e8d3779-e19f-4579-a811-ac28f975bdd3)

**Comment by johnbao6** [comment]
我也有点累了，明天再说。谢谢您！

**Comment by xaoxuu** [comment]
我也没辙了，不过还有一个办法可以尝试，就是用 GitHub Codespaces

**Comment by panoshu** [comment]
我之前的github codespace中也遇到过这个问题，包括在github workflow中也遇到这个问题。不过是偶尔出现，当时就是 `hexo cl` 几次后，再 `hexo g` ，再执行 `hexo s` ，如果报这个错误就重复执行一下，然后就不报错了。后来我在codespace中使用 yarn 重装了全局 hexo-cli，并把yarn的全局包路径加到 path 变量中，这几天就再也没有出现过这个错误了。供参考。

**Comment by tksmly** [comment]
这个问题似乎是<https://github.com/xaoxuu/hexo-theme-stellar/commit/016d75f1ba0232658a88aba00acb45f7e3ccf612>导致的,1.25版本没有问题
这个提交改动太多了很难排错🤯

**Comment by xaoxuu** [comment]
1.27.0 能用吗

**Comment by tksmly** [comment]
> 1.27.0 能用吗

1.25以后的所有版本都存在这个问题,复现方式是多次运行`hexo g`,clean之后首次运行正常

**Comment by xaoxuu** [comment]
我没有遇到过，反复操作也无法复现

**Comment by xaoxuu** [comment]
我改了下名字，如果更新 node 之后依然无效，可以测试一下这个分支： https://github.com/xaoxuu/hexo-theme-stellar/tree/test

**Comment by songtianlun** [comment]
> @songtianlun 麻烦 node 更新到 `20.10` 看看还能复现不？

试了一下，在 main 分支下现象一致：
```bash
node -v 
v20.12.2
node -v
v18.18.2

hexo server # 正常
Ctrl-C
hexo server # 异常

hexo server # 正常
Ctrl-C
hexo clean
hexo server # 正常
```

test 分支下一切正常

```bash
node -v 
v20.12.2
node -v
v18.18.2

hexo server # 正常
Ctrl-C
hexo server # 正常
```

**Comment by xaoxuu** [comment]
那看来是文件夹命名引起的奇怪冲突？

**Comment by tksmly** [comment]
1.28.1可以正常使用🥳🥳🥳

**Comment by xaoxuu** [comment]
看起来类似于曾经的 noteblock 问题，未解之谜，改名字就好了。
