### ISSUE TITLE
左上角头像下标签不显示，点击文章内容报错，

### ISSUE THREAD

**Issue by loohalh** [xaoxuu/hexo-theme-stellar#379]
新建博客，作者的博客配置很高大上，所以准备在作者博客的基础上改，在博客文件下，hexo init之后使用 npm i hexo-theme-stellar 安装了stellar，使用作者博客的源码配置，把_config.yml、_config.stellar.yml文件复制替换，source和scaffolds文件下所有文件也已替换，左上角头像下标签(sidebar->menu)不显示，点击文章内容报错，大佬给看看是我哪儿配置不对吗

环境如下
`hexo: 7.1.1
hexo-cli: 4.3.1
os: darwin 22.6.0 13.5

node: 20.10.0
acorn: 8.10.0
ada: 2.7.2
ares: 1.20.1
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.1
icu: 73.2
llhttp: 8.1.1
modules: 115
napi: 9
nghttp2: 1.57.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.12+quic
simdutf: 3.2.18
tz: 2023c
undici: 5.26.4
unicode: 15.0
uv: 1.46.0
uvwasi: 0.0.19
v8: 11.3.244.8-node.25
zlib: 1.2.13.1-motley`

 _config.yml文件如下：
<img width="994" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/566cac58-f2ed-49f9-b254-5394b09aa2e8">
<img width="881" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/34a77249-85f7-40c9-80e5-3b4311d156e3">
<img width="982" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/4eb6692f-d115-4c85-94e4-f57099c2abc5">

_config.stellar.ymll文件如下：
<img width="703" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/f13ea81a-bb52-4b72-b139-05283ab3038a">

source文件夹
<img width="755" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/f6fdfb2e-18aa-4655-ad5c-57743d6c6228">

source文件下安装脚本也报错
<img width="642" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/add7fa1d-febb-49cc-bc8e-c8cc9a08f067">

点击文章报错信息如下
<img width="1051" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/1e4e12e0-541d-4c8c-a906-3d9fb4c11856">

**Comment by xaoxuu** [comment]
不要刻舟求剑拿远古版本的源码配最新的主题，肯定会报错的。建议正儿八经按照文档推荐的方法使用。

> [安装与更新](https://xaoxuu.com/wiki/stellar/#%E5%AE%89%E8%A3%85%E4%B8%8E%E6%9B%B4%E6%96%B0)

想省事的话可以直接下载我最近发布的示例源码： https://github.com/xaoxuu/hexo-stellar-starter

**Comment by loohalh** [comment]
嗯嗯 按照文档和搜索来的方法准备添加侧边栏sidebar:menu: 的形式显示样式，用你最新代码https://github.com/xaoxuu/hexo-stellar-starter的配置，还是无法显示标签侧边栏，需要怎么配置sidebar:menu:

**Comment by loohalh** [comment]
> 不要刻舟求剑拿远古版本的源码配最新的主题，肯定会报错的。建议正儿八经按照文档推荐的方法使用。
> 
> > [安装与更新](https://xaoxuu.com/wiki/stellar/#%E5%AE%89%E8%A3%85%E4%B8%8E%E6%9B%B4%E6%96%B0)
> 
> 想省事的话可以直接下载我最近发布的示例源码： https://github.com/xaoxuu/hexo-stellar-starter

嗯嗯 按照文档和搜索来的方法准备添加侧边栏sidebar:menu: 的形式显示样式，用你最新代码[https://github.com/xaoxuu/hexo-stellar-starter的配置，还是无法显示标签侧边栏，还是说需要怎么配置sidebar:menu 才能显示为带标签的侧边栏切换的，想要的效果如下：
<img width="158" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16890588/cf5cb1e9-5e22-416a-99b5-ceefb41c0023">

**Comment by xaoxuu** [comment]
我再次确认了下 starter 示例，已经是新的写法了，而你刚回复的依然是老的写法，我不知道你在哪里看的过时文档。

**Comment by xaoxuu** [comment]
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/8f6efc0f-7ea9-418e-8fb9-262a86b2aed6)

![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/48130b13-baca-4e06-9124-da07f16ea254)

**Comment by xaoxuu** [comment]
你是不是还在拿22年以前的源码往配置文件里去替换啊，这个公告我都公示一年半了。旧的源码已经不适用于新的主题了。

**Comment by xaoxuu** [comment]
而且你截的这个图也是至少半个月前的了，能告诉我你在哪看到的吗？怀疑是不是又有人克隆我的网站了。

**Comment by loohalh** [comment]
> 我再次确认了下 starter 示例，已经是新的写法了，而你刚回复的依然是老的写法，我不知道你在哪里看的过时文档。
事情是这样的，我安装最新的主题版本，按照你的教程配置完了之后，navbar都是你最新的样式，带图标的这种，因为之前在看过有其他人的博客是老版本，显示样式是标签tab的样式，我想要简洁明了一点的显示方式（标签tab的样式），所以就搜索查看别人的教程贴，他们写教程时应该还是老版本，所以才产生这样的问题

**Comment by xaoxuu** [comment]
那需要指定 1.25.0 或之前的版本，1.26.0 版本开始写法和样式都变了。

**Comment by loohalh** [comment]
> 那需要指定 1.25.0 或之前的版本，1.26.0 版本开始写法和样式都变了。

那应该是。我明白了， 搞这个搞了好久 百思不得其解，新版自定义的话 图标不太好找，想着还是文字tab切换简介明了，新版本有办法使用tab切换吗

**Comment by xaoxuu** [comment]
新版也是支持纯文字的，只要不设置icon就可以。

**Comment by loohalh** [comment]
> 新版也是支持纯文字的，只要不设置icon就可以。

试了下 样式有点丑 哈哈哈 暂时先这么用吧 谢谢啦

**Comment by loohalh** [comment]
> 新版也是支持纯文字的，只要不设置icon就可以。

有希望能支持 老版本和新版本样式都可以用的吗 改动不大的情况下

**Comment by xaoxuu** [comment]
旧UI不适合有背景、按钮数量超过1行的情况，新的UI适应性好。后续版本会想办法优化的，可以继续关注后续更新。

**Comment by loohalh** [comment]
> 旧UI不适合有背景、按钮数量超过1行的情况，新的UI适应性好。后续版本会想办法优化的，可以继续关注后续更新。

好的 谢谢 幸苦啦 我把这个关了

**Comment by xaoxuu** [comment]
🤝
