### ISSUE TITLE
侧边栏在不同页面的顶部边距异常

### ISSUE THREAD

**Issue by celaraze** [xaoxuu/hexo-theme-stellar#380]
开始以为我配置问题，折腾了后从大佬博客站点也发现了这个问题。

直接上图：

![1](https://github.com/xaoxuu/hexo-theme-stellar/assets/31471452/c6e55daa-d0a7-4a32-8ce8-76be971467b3)

![2](https://github.com/xaoxuu/hexo-theme-stellar/assets/31471452/b3ec2514-8734-4797-a452-ae7865f0f4c0)

**Comment by xaoxuu** [comment]
你观察到好仔细😂

**Comment by celaraze** [comment]
> 你观察的好仔细😂

嘿嘿，感谢修复，感谢付出。🙏
