### ISSUE TITLE
功能建议：为 navbar 标签添加样式

### ISSUE THREAD

**Issue by parasolwaddledee** [xaoxuu/hexo-theme-stellar#381]
建议为 navbar 标签添加类似于 blog 和 wiki 顶部导航栏的样式，使其在作为独立页面的顶部导航栏时与后者的表现一致：

![2024-02-02_115945](https://github.com/xaoxuu/hexo-theme-stellar/assets/105424387/504496a5-dfab-4102-a771-39682aaea5ab)

**Comment by xaoxuu** [comment]
99efcfe96c3346f70520abf10a406d24f8742bf6

**Comment by parasolwaddledee** [comment]
高产！
