### ISSUE TITLE
分类、标签和归档页面顶部显示异常

### ISSUE THREAD

**Issue by gsh1209** [xaoxuu/hexo-theme-stellar#383]
在页面内容不满一页时，可能会出现顶部间距消失的问题

正常情况：
![20240202180458](https://github.com/xaoxuu/hexo-theme-stellar/assets/113790912/7da7a3e2-e4f2-42bd-b994-cb41921b3925)

间距消失（标签页内容较少，不满一页）：
![20240202180621](https://github.com/xaoxuu/hexo-theme-stellar/assets/113790912/90bdc868-53b0-44e7-ba14-ac612e681b01)

说是*可能出现*的原因是，在一些博客中，即使内容不满一页也能正常显示
在[使用 Stellar 主题的博客](https://xaoxuu.com/wiki/stellar/examples.html)中点开了几个，显示异常的例子
- [blog1](https://easyf12.top/tags/)
- [blog2](https://sumorio.com/categories/)
- [blog3](https://waddledee.com/categories)

显示正常的例子：
- [blog4](https://xaoxuu.com/blog/tags)
- [blog5](https://celaraze.com/tags/)
- [blog6](https://blog.zhilu.cyou/categories/)

出现问题的版本信息(hexo 版本从7.1.1 降级至 7.0.0 再到 6.3.0 均会出现这个问题)：

```
INFO  Validating config
INFO  Welcome to Stellar 1.26.4
DOCS  https://xaoxuu.com/wiki/stellar/
REPO  https://github.com/xaoxuu/hexo-theme-stellar.git

hexo: 6.3.0
hexo-cli: 4.3.1
os: win32 10.0.19045
node: 18.18.1
acorn: 8.10.0
ada: 2.6.0
ares: 1.19.1
brotli: 1.0.9
cldr: 43.1
icu: 73.2
llhttp: 6.0.11
modules: 108
napi: 9
nghttp2: 1.55.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.10+quic
simdutf: 3.2.14
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.18
v8: 10.2.154.26-node.26
zlib: 1.2.13.1-motley
```

**Comment by gsh1209** [comment]
在显示不正常的页面将浏览器取消最大化，调整窗口尺寸小到不能完整显示页面内容（即内容超出一页），顶部间距就会恢复正常

**Comment by xaoxuu** [comment]
你看看跟 #380 和 #382 是不是一样的

**Comment by gsh1209** [comment]
打扰了。。
