### ISSUE TITLE
所有页面出现不适配问题

### ISSUE THREAD

**Issue by chentaiyang** [xaoxuu/hexo-theme-stellar#389]
请看图
[![pF30wvT.png](https://s11.ax1x.com/2024/02/10/pF30wvT.png)](https://imgse.com/i/pF30wvT)
无法正常显示，左边一大片空白，请问如何解决
第一次Issues，不太了解，希望加个微信好友new003a指导，谢谢

**Comment by xaoxuu** [comment]
你认为应该铺满页面不留空隙吗？

**Comment by chentaiyang** [comment]
你的博客他就是全铺满的哇~

**Comment by xaoxuu** [comment]
你指的具体是哪里的空白，我看你给的图是符合设计预期的

**Comment by chentaiyang** [comment]
左侧和右侧有空白，你的那个就没有空白完全填充

**Comment by xaoxuu** [comment]
估计是因为我用的是正在开发中的三栏设计，相对来说会比老版本宽一点，但其实网页如果拉的更宽一点，还是会居中，左右留白的。
喜欢3栏的话可以等新版本。
