### ISSUE TITLE
关于主题，提供10点建议，仅供参考

### ISSUE THREAD

**Issue by g0fcn** [xaoxuu/hexo-theme-stellar#391]
刚开始用这个主题，就我觉得颜值这方面绝对是hexo最能打的，感谢大佬
下面是我的建议
（不一定要更新，仅为作者提供更新灵感）

ps:下方都是我的天方夜谭，仅供参考

1.ai摘要（按字数付费的，用着心疼😣）
可以考虑用那些让我们自己提供接口和key的，gpt3.5的接口可以免费提取，Gemini也是免费的。目前这方面的ai提取插件也有很多，没必要一定要那个付费的

2.菜单栏上方的目录按钮，希望可以有开关
（如果有请告知）
ps:我用wordpress的，类似于这些功能我是能不开就不开，生怕影响打开速度

3.总感觉网站右上角有点空旷，而目前现在的菜单，说实话不太容易被发现，不过总感觉右上角放菜单有些多余，可以考虑搜索放那个位置，最好可以自定义，感觉目前的搜索好像有点bug，反应不太灵敏

4.手机版可以这样![IMG_20240214_151725.jpg](https://github.com/xaoxuu/hexo-theme-stellar/assets/156695055/ce8bce18-f0cb-4295-9ef2-d26e2c062c2e)缩略图在右侧，宽度低点，标题和摘要放坐标，甚至可以加一个（点击阅读）
按钮，目前hexo主题的手机版文章貌似都有点“臃肿”，一篇文章可以占用2/3个手机屏幕

5.页面底部空白有点大
试问江南诸伴侣，谁似我，醉扬州。本站由 xaoxuu 使用 Stellar 1.26.8 创建，至今已持续稳定运行七年。
这个下面

6.![IMG_20240214_152809.jpg](https://github.com/xaoxuu/hexo-theme-stellar/assets/156695055/78a74756-e2ad-4498-8128-04c92314503b)

这个位置最好有主页头或者logo，点击可以返回主页，感觉这样不利于读者返回主页，虽然可以点击那个主页文字返回

7.总结下，总感觉作者所有功能都偏左，就我自己来说，感觉很难受，总想在右边，点点啥，右边或许空旷

8.seo这方面，不知道是不是hexo本身不利于收录还是别的什么原因，玩hexo至今，最高看到的hexo博客百度权重只有1，希望每个页面头都添加seo元素，这样咱们也能更好的宣传该主题，最后一个建议，朋友圈可以有接口自动检测域名的权重嘛并形成权重标记显示
（这样我就能一眼看到流量大佬了，哈哈哈）

9.大佬你的主题使用文档感觉没有衔接性，或者说标题没有针对性，不太好使用，目前看的最多的就是第一页，拉取主题…
对了，插件版本最好带上，就比如相关文章，我试了很多版本才找到兼容的，像我这种所有数据都在github的，用action执行的真的很需要

10.这应该是我想象了，凭空捏造，前段时间一直想做一个国际站，毕竟github网站，国际站才是最有前途的，但是多需要这方面真的太伤了，要自己自己翻译，我就想都有ai了，能不能来个根据中文文章自动生成多国语言md文件功能，或者根据中文自动在本身的md文件中生成多国需要文章，再不济直接可以ai翻译

**Comment by xaoxuu** [comment]
1. 这个是其他大佬 PR 的，我对这块功能不太懂
2. items 设置为空数组即可
3. [组件库](https://xaoxuu.com/wiki/stellar/widgets/) 中的任何一个组件理论上都可以放在左右两个侧边栏中，但是部分没有进行 UI 适配，可以自行斟酌选用。
4. 你觉得“臃肿”主要是因为摘要部分占用篇幅较多，如果改成左侧缩略图的话，文字区域变窄，同样内容会占用更多的纵向空间，会更“臃肿”，所以参考效果能显示更多文章项的关键是没有摘要。另外，不是所有人的所有文章都有缩略图，这样设计灵活性较差。
5. 这个是整体风格就是这样，想紧凑一点可以自己调一下。
6. 我看了描述认为你的主要诉求是返回主页占用的视觉空间太小了，希望大一点。这个是我特意设计如此的，理由是增加本文阅读沉浸感。同时由于返回主页按钮是该页面的第一个视觉元素，用户应该不至于看不见。很多网站都有面包屑导航，我认为这是有共识的设计，不需要凸显出其他页面的链接来喧宾夺主。
7. 同3，左右两侧都可以自己选择放置组件。
8. 我不太清楚百度权重，我平时用bing/google，感觉都是秒收录的。
9. 文档是开源的，欢迎PR。插件带上版本是个好建议，后续会尽量补上。至于具体的这个case，相关文章插件用最新版本 [5.0.1](https://www.npmjs.com/package/hexo-related-popular-posts) 就是兼容的。（你还可以看到我的PR）
10. 技术方面，同第1条，我不是太懂；体验方面，我认为提供一个机翻站就是内容农场，不建议这样做，读者不喜欢，搜索引擎也不喜欢。

**Comment by xaoxuu** [comment]
我看了下你的博客，封面基本上都和内容无关，建议通过去掉封面的方式来提高显示密度。
