### ISSUE TITLE
waline 3.0适配问题

### ISSUE THREAD

**Issue by panoshu** [xaoxuu/hexo-theme-stellar#395]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

waline升级到3.x版本以后，会出现无法加载评论的情况，尝试着调试了一下，控制台报错“Uncaught (in promise) ReferenceError: Waline is not defined”。

问题应该出在“layout/_partial/comments/waline/script.ejs”文件里面对js的加载方式上。

在waline官方的issues中搜索了一下，提到“3.0 正在尝试使用 ES Module 作为默认导出形式，所以不能使用普通的方式做加载。”。

可能需要修改主题的`utils.ejs`中加载js的逻辑。我不懂前端，改不来。。。为了便于调试，我把我的博客的waline升级到了3.0版本，可以调试看下。地址：[https://www.panoshu.top](https://www.panoshu.top)

**Comment by xaoxuu** [comment]
我按照官网方法接入能接，但是似乎不能使用 `<%- JSON.stringify(theme.comments.waline) %>` 这类语法读取配置，只能全都写死了。

**Comment by xaoxuu** [comment]
你更新一下看看，我只做了最基础功能的接入。

**Comment by panoshu** [comment]
我尝试按照官方的客户端例子改了下，可以用了。提交了PR。

**Comment by panoshu** [comment]
感谢大佬，之前没看到你的回复。我中午尝试按照官方的客户端例子也改了下，可以用。提交了PR。
ps: 不过我改的那个是直接升级了v3版本，没有保留2.x版本的配置，逻辑和v2版本差不多，可以使用waline配置项下面的其他参数。大佬看下要不要合并，如果不合并的话，就把PR关掉好了。

**Comment by xaoxuu** [comment]
升级到v3改动量大不大？不大的话就不保留旧版了

**Comment by panoshu** [comment]
> 升级到v3，服务端那部分改动量大不大？不大的话就不保留旧版了

waline服务端升级下版本就可以了，配置没变化。
