### ISSUE TITLE
关于微博widget

### ISSUE THREAD

**Issue by wxydejoy** [xaoxuu/hexo-theme-stellar#398]
### 检查清单

- [x] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

目前的微博widget使用的是爬虫数据，需要经常更新cookie，较为麻烦，可否考虑使用rsshub的数据，无需cookie就可以显示最近的10条内容，也不用部署什么的
链接
[doc]( https://docs.rsshub.app/routes/social-media#wei-bo-bo-zhu)
示例 
[rss](https://rsshub.app/weibo/user/1195230310)

**Comment by xaoxuu** [comment]
这个暂时没有计划，建议您自己来适配一下
