### ISSUE TITLE
黑暗模式使用过程中在手机上的显示问题

### ISSUE THREAD

**Issue by yeelvus** [xaoxuu/hexo-theme-stellar#402]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [ ] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

如图，在异形屏手机上黑暗模式有这个条条，不知道如何设置可以可以让全部变黑。同时是否可以加入黑暗模式的选择开关，觉得加一个开关回更好用🥲
望解答，提的不对的地方还请见谅。

![IMG_8811](https://github.com/xaoxuu/hexo-theme-stellar/assets/50106230/8a892da4-ccde-4bb5-8b02-f71d39df68bb)
![IMG_8812](https://github.com/xaoxuu/hexo-theme-stellar/assets/50106230/7ca4d4e1-e385-4757-889d-90b17312d610)

**Comment by xaoxuu** [comment]
上面那个条的颜色是在html里写的，我不太清楚怎么动态支持。

**Comment by xaoxuu** [comment]
现在已经跟随主题了

**Comment by yeelvus** [comment]
感谢大佬的更新，希望主题越来越好。
