### ISSUE TITLE
我的references 资料引用显示不正确，格式是按照

### ISSUE THREAD

**Issue by Readfere** [xaoxuu/hexo-theme-stellar#415]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

我的references 资料引用显示不正确，格式是按照文档给的格式写的，我放到了一篇文章的末尾
```
---
references:
   - '[IPAdown](https://www.52pojie.cn/thread-1863801-1-1.html)'
   - '[Sideloadly](https://sideloadly.io/)'
---
```
<img width="401" alt="42gs5t4y qre" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/152289805/0c54a5fb-5cd2-4a80-b7da-277b6daf5925">

**Comment by weekdaycare** [comment]
这是让你放在font-matter中，不是放在文章里
