### ISSUE TITLE
stellar 主题中的文件放在哪个目录下？

### ISSUE THREAD

**Issue by johnbao6** [xaoxuu/hexo-theme-stellar#416]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [ ] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

装好 Hexo 后，运行 以下命令 npm i hexo-theme-stellar, 然后在 _config.yml 文件中修改 theme: stellar, 也出现了 stellar 风格的主题，似乎一切都很正常，但是当我想看看 themes 文件夹下有哪些文件时，竟然发现是空的。

stellar 主题中的文件放在哪个目录下？

**Comment by weekdaycare** [comment]
当你使用稳定版安装时主题目录位于`node_modules`文件夹下

**Comment by johnbao6** [comment]
很奇怪的做法，themes文件夹还有什么意思？还不如删除了

**Comment by weekdaycare** [comment]
如果你是使用最新版或者自定义的话主题文件是在themes下的，这是给想要尝鲜或者需要改动主题源码的人准备的

**Comment by L33Z22L11** [comment]
通过npm安装的主题并不是给用户修改用的，许多操作（update或者在新的环境中build）都有可能让你的主题恢复至官方版本。

如需修改主题，请使用git clone方式。

**Comment by johnbao6** [comment]
谢谢大家给的建议。
我还是认为这种做法是非常怪异的，而且似乎也没有教程解释它，或许是因为怪异本身就很不自然，故而在教程中也很难解释清楚。
Hexo 本来是为了让新手很容易上手，但是这个怪异的做法只会让新手迷惑不解。
与其这样，还真的不如删了 themes 文件夹和 _config.landscape.yml 文件。

**Comment by L33Z22L11** [comment]
既然提到了 landscape ， hexo 的默认主题 hexo-theme-landscape 也是作为 npm 包存在于 node_modules/ 目录下，而不是位于 theme/ 目录下，并且在 [README](https://github.com/hexojs/hexo-theme-landscape?tab=readme-ov-file#install) 中向用户提供了 npm 安装方式。你也可以向他们提出这个 issue，来获得解答。

**Comment by xaoxuu** [comment]
@johnbao6 
- 存放在 `node_modules` 的部分是由 node 决定的
- 存放在 `themes/` 的部分是由 hexo 决定的
对上述哪种做法感到怪异可以去对应的项目中提 issue ，本项目本质上只是 hexo 的一个“插件”，改变不了 hexo 的规则，更改变不了 node 的规则。

**Comment by johnbao6** [comment]
谢谢两位的解释。

老实说，我一开始使用 Hexo 时，就被其中的目录结构给弄糊涂了。
我看到的所有教程（中文或英文的）都是把主题中的文件放在 themes 下面的，而我的却不是的，一开始以为只是我自己的问题，虽然基本上不影响使用。
