### ISSUE TITLE
代码块复制按钮无法正常使用

### ISSUE THREAD

**Issue by MiaoXsong** [xaoxuu/hexo-theme-stellar#417]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

点击代码块的复制按钮后，出现如下情况，并且无法正常使用
![1711790706581](https://github.com/xaoxuu/hexo-theme-stellar/assets/96432890/7329990d-5b3f-46ce-99c2-353beb73628a)

尝试更换浏览器测试（Edge、Chrome、以及手机浏览器），也尝试重新更换过云服务器系统与版本（Linux系统），本地虚拟机也测试过，依旧是相同问题，但是我访问官方博客网站：https://xaoxuu.com/ 以及一些带有该功能的友链博客是正常的

当前环境：
系统：Ubentu 22.04（曾更换过centos stream 9、 anolis7.9）
node：v18.20.0（曾更换过16 和 20）
hexo: 7.1.1（曾更换过7.0.0）
hexo-cli: 4.3.1

hexo配置文件以及stellar配置文件均未更改

**Comment by L33Z22L11** [comment]
仅在安全上下文（HTTPS）中可用。参见 [Navigator：clipboard 属性](https://developer.mozilla.org/zh-CN/docs/Web/API/Navigator/clipboard)。

**Comment by MiaoXsong** [comment]
谢谢，经验证添加HTTPS后就可以正常使用了
