### ISSUE TITLE
功能改进建议：能否增加一个选项设置为纯 wiki 显示（首页去掉 blog）

### ISSUE THREAD

**Issue by Tikas** [xaoxuu/hexo-theme-stellar#42]
### 构思来源：

wiki 模式非常新颖，并且具有非常直观的顶条分类显示导航。

网站首页进来默认是 blog 内容，总感觉不出我那精心打造的 wiki 内容。

### 改进建议：

- [x] 配置文件里增加一个是否启用纯 wiki 选项
- [x] wiki 配置能否同 blog 文章那样简化，以免 wiki 项目太多，导致容易错乱
- [x] wiki 封面显示增加可以同 blog 那样的文章封面卡片。如此：wiki 就等于包含了 blog，不同的项目可以有更多个性选择 
- [ ] 未完待续...

### 来自内心灵魂的发声：

xaoxuu 真帅！

**Comment by MuziShaoxing** [comment]
这个我现在就在使用。。。https://hackintool.netlify.app/你看看想要的是不是这个

**Comment by xaoxuu** [comment]
@MuziShaoxing 厉害啊👍 建议提个PR

如果全站只有一个wiki，那么这两个地方其实也可以去掉了：
<img width="693" alt="image" src="https://user-images.githubusercontent.com/16400144/142654215-2fa168ac-94f9-4a09-ad20-5aefc8b9c2cd.png">

**Comment by Tikas** [comment]
太强了，今天点 github 导航的 lssues ，发现能查看所有我提过的，现在才看到，实现的非常不错，最近我跑到 vuepress 去了，😂

**Comment by xaoxuu** [comment]
先挖个坑，有空了做一下，支持一键设置：
```yaml
root: blog/wiki/docs 
```
- `blog`: 首页是普通主题的博客页面
- `wiki`: 首页是项目列表（wiki）页面
- `docs`: 首页就是一个项目的主页，类似于 `docsify`

**Comment by xaoxuu** [comment]
已经提供了demo： https://github.com/xaoxuu/hexo-stellar-starter
