### ISSUE TITLE
建议增加一个注释标签

### ISSUE THREAD

**Issue by MuziShaoxing** [xaoxuu/hexo-theme-stellar#43]
![09:34-XCDWZH](https://cdn.jsdelivr.net/gh/muzishaoxing/Picture@main/shaoxing/20211001/09:34-XCDWZH.png)
![image](https://user-images.githubusercontent.com/76191512/135552736-6fa063f1-8321-4c2c-8079-c5feffbee49e.png)

如图，
具体作用：填写注释信息，鼠标悬浮弹出，（其实现在的。 密码标签 “条条”改成“可自定义”就可以用）

**Comment by MuziShaoxing** [comment]
![13:22-multi-line-screencast](https://cdn.jsdelivr.net/gh/muzishaoxing/Picture@main/shaoxing/20211001/13:22-multi-line-screencast.gif)这个玩意也不错 嘿嘿

**Comment by xaoxuu** [comment]
接一下这个插件可以实现：https://github.com/etigerstudio/hexo-tag-hint
