### ISSUE TITLE
recent内容不对

### ISSUE THREAD

**Issue by cayzlh** [xaoxuu/hexo-theme-stellar#44]
侧边栏的recent理论上是显示最近新增的文章，但是， 我的一直在展示很久以前的内容，而且上面显示的时间也是上一次部署的时间。 

![image](https://user-images.githubusercontent.com/12791269/140250400-ec70696c-c02b-41b7-89f3-9da1d88cb237.png)

如图所示。

这些内容都是很久以前的了。 ，这里上面显示的11月3号是因为我升级了主题之后部署的时间。

一直不知道问题出在哪， 麻烦大佬有空看看。

**Comment by abnerwei** [comment]
文章没有配置 `updated` 就会默认使用文件编译时间

**Comment by cayzlh** [comment]
> 文章没有配置 `updated` 就会默认使用文件编译时间

3Q， 我试试

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/xaoxuu.github.io/blob/43c2a07271ac5c0338d2af63a768fce5dfe8a600/_config.yml#L89-L90
