### ISSUE TITLE
请问静态时间线可以做成组件部署到侧边栏吗？

### ISSUE THREAD

**Issue by aRanHC** [xaoxuu/hexo-theme-stellar#447]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [x] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [x] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

你好，作者大大，感谢做出这么好看的主题!
我想请问比如专栏新写了一篇文章、或者文章做了一点修改，我就新加一条`<!-- node x 年 x月 x日 -->`记录一下修改内容呈现在侧边栏上。目前可以实现吗？

**Comment by xaoxuu** [comment]
目前好像不支持静态写法，你可以在github仓库上建个release来写，就跟发版本一样。

**Comment by aRanHC** [comment]
好主意，感谢回答！🦀🦀
