### ISSUE TITLE
自定义代码高亮时，代码块出现问题

### ISSUE THREAD

**Issue by aRanHC** [xaoxuu/hexo-theme-stellar#453]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题
使用其它 highlight.js 代码高亮主题时代码块外面多了一层容器，而且复制按钮消失
### 截图
设置前：
![1](https://aran-bucket1.oss-cn-beijing.aliyuncs.com/img_forMarkdown/20240501223347.png)
设置后：
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/130441914/0cac0f4e-673e-4b8f-9c22-003955ec0f8c)
#### _config.yml
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
#### _config.stellar.yml
style:
  codeblock:
    highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark-reasonable.min.css
### 参考解决方案
https://github.com/xaoxuu/hexo-theme-stellar/issues/296 中有相同问题，但是解决的方案现在看不了了还请大佬们帮忙看一下。

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/issues/296#issuecomment-1555580394

**Comment by NING0121** [comment]
> [#296 (comment)](https://github.com/xaoxuu/hexo-theme-stellar/issues/296#issuecomment-1555580394)

@xaoxuu 不好意思，还想请问一下，我已经设置了对应的_config.yml项，但好像仍有相同的问题？
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/61087497/899b65a7-dcf4-411e-9cff-c94d51c8e637)
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/61087497/a65be792-3a5b-4eea-9ad2-6561a1ae595e)
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/61087497/4a2269c7-f828-43e3-9444-a037baa5963d)

**Comment by NING0121** [comment]
> > [#296（评论）](https://github.com/xaoxuu/hexo-theme-stellar/issues/296#issuecomment-1555580394)
> 
> @xaoxuu不好意思，还想请问一下，我已经设置了对应的_config.yml项，但好像仍有相同的问题？ ![图像](https://private-user-images.githubusercontent.com/61087497/346448383-899b65a7-dcf4-411e-9cff-c94d51c8e637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjE2MTAsIm5iZiI6MTcyMDQyMTMxMCwicGF0aCI6Ii82MTA4NzQ5Ny8zNDY0NDgzODMtODk5YjY1YTctZGNmNC00MTFlLTljZmYtYzk0ZDUxYzhlNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTYxY2QwZWM4NGYwODFlNzAyMjJjMTY4NTY5OGE0N2YyMmFmZmFlYzg1OTVmZWY2ODAyNWViMGY2YzdlZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXIxgPphWi8CaOAlwg5BxyJNcVjlNzVzuDjC43_WGVk) ![图像](https://private-user-images.githubusercontent.com/61087497/346448436-a65be792-3a5b-4eea-9ad2-6561a1ae595e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjE2MTAsIm5iZiI6MTcyMDQyMTMxMCwicGF0aCI6Ii82MTA4NzQ5Ny8zNDY0NDg0MzYtYTY1YmU3OTItM2E1Yi00ZWVhLTlhZDItNjU2MWExYWU1OTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZWY0NTczNWViMzk4ZDU5ZjBkMjkwMjBhNWY3ZjlmMjVmMzBlZTBjMjFhZWQwNDFhNDEyOGM1ODE3Mjg2MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VXcS_4yuHbwVj0DIieU0hxktbPA_nO6ZQtAtDtXPlSE) ![图像](https://private-user-images.githubusercontent.com/61087497/346448482-4a2269c7-f828-43e3-9444-a037baa5963d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjE2MTAsIm5iZiI6MTcyMDQyMTMxMCwicGF0aCI6Ii82MTA4NzQ5Ny8zNDY0NDg0ODItNGEyMjY5YzctZjgyOC00M2UzLTk0NDQtYTAzN2JhYTU5NjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYjdhMTU0NmUwM2ZhMzg4ZTU5YzVkMjlmNmVkOGNhNjA0NGM5OGY4NjY3NjJkZGJiMzRjZDQ0MmIzYjkxZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BjRo8BG8iyVmlH5h-ciHeX9LuCDJgBdZ9DsuKKuo3uw)

我已经找到了问题的所在，是我搞错了，我以为codeblock/tabs要都保留，对我来说仅需要保留codeblock即可。
