### ISSUE TITLE
能不能给一个完整的_config.stellar.yml 包含site tree 的写法，真的怎么试都试不出来

### ISSUE THREAD

**Issue by lovedva** [xaoxuu/hexo-theme-stellar#456]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

官方博客主页显示的侧边栏配置，leftbar sidebar menubar 都试过了怎么都配置不了，怎么改主题配置都没反应，应该是配置的写法不对，到处找找不到合适的例子，真的尽力了，能不能一个完整的写法参考一下。
以及side tree，想在博客主页的左侧栏加上widgets，配置到底应该怎么写，真的各种写法都试过了，一个都没用。
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/7524140/4861f829-55c1-4cde-adff-618195147443)

**Comment by weekdaycare** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/blob/main/_config.yml

**Comment by lovedva** [comment]
> https://github.com/xaoxuu/hexo-theme-stellar/blob/main/_config.yml

谢谢，好人一生平安！
