### ISSUE TITLE
[Bug] Welcome 寫死 theme config 將難以覆寫

### ISSUE THREAD

**Issue by iknowright** [xaoxuu/hexo-theme-stellar#46]
![code](https://user-images.githubusercontent.com/25934612/141436010-cea5c73d-7c04-47b8-bfd1-9f0b16c4b758.png)

若使用者使用 `_config.stellar.yml` 更新 welcome content 是無法覆寫原本 theme config 的，除非 fork 再改 source code。

建議：
將 content 內容註解或者更新 stellar docs 讓使用者可以理解之間的差異

Ref:
https://hexo.io/zh-tw/docs/configuration.html#Alternate-Theme-Config

**Comment by xaoxuu** [comment]
- 目前按照 `welcome` 里面的提示操作，即使用 `_data/widgets.yml` 覆盖是可以的。
- 稍后的版本我打算把 `content` 由数组结构改为字符串结构，这样就也可以在 `_config.stellar.yml` 中进行覆盖了。
