### ISSUE TITLE
在哪里设置永远显示黑暗模式？

### ISSUE THREAD

**Issue by ichubei** [xaoxuu/hexo-theme-stellar#472]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [ ] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

感觉黑暗模式好看，不想让黑暗模式自动改变，在哪设置呢？

**Comment by calfzhou** [comment]
`_config.stellar.yml`:

``` yaml
style:
  prefers_theme: dark # auto / light / dark
```

**Comment by ichubei** [comment]
多谢
