### ISSUE TITLE
KaTeX hexo-renderer-markdown-it-plus 插件兼容问题

### ISSUE THREAD

**Issue by hermitlsr** [xaoxuu/hexo-theme-stellar#476]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

在使用 `katex` 时需要更换默认的 `markdown` 渲染器，即：

>  # 使用 hexo-renderer-markdown-it-plus 作为公式渲染器：npm uninstall hexo-renderer-marked --save npm install hexo-renderer-markdown-it-plus --save

更换后会导致文章标题丢失样式：

会由此： `<a class="markdownIt-Anchor" href="#1-写在前面"></a>` 

![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/84276102/e74298a6-a2b1-47a0-9e61-fce6bd9d22d5)

 
更换为： `<a href="#1-写在前面" class="headerlink" title="1 写在前面"></a>`

![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/84276102/6a32ab15-edae-43f2-8584-76a95659d50b)

需要额外兼容

**Comment by KazariEX** [comment]
主题里的部分样式绑定了 marked 渲染器所生成的类名，不应该直接更换渲染器，这部分代码逻辑可能需要更新

**Comment by calfzhou** [comment]
那现在用 katex （行内公式）的话，也还是要用 hexo-renderer-markdown-it-plus ，只是样式恢复了？还是说不换 renderer 也可以正常使用 katex？

我现在用 hexo-renderer-markdown-it-plus，主题更新到最新，但标题样式还是没有。

**Comment by KazariEX** [comment]
需要换 renderer，主题还没发布新版本所以暂时看不到标题样式

**Comment by calfzhou** [comment]
我引的是 master 分支，更新到最新提交了。

<img width="914" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/3761553/e5b393c1-1c78-483f-b7a1-9de7645e93f7">

node modules 里 主题包里的代码已经是最新的了。


貌似我的标题部分，都是没有 `<a>` 标签的，是我 hexo-renderer-markdown-it-plus 没配置好么。

<img width="295" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/3761553/85ec841d-b66b-4b96-bd96-10908444ef14">

**Comment by calfzhou** [comment]
好了，需要改一下 hexo-renderer-markdown-it-plus 的配置，类似这样：

``` yaml _config.yml
markdown: # https://github.com/hexojs/hexo-renderer-markdown-it
  preset: 'default'
  anchors:
    permalink: true
    permalinkSymbol: ''
```

**Comment by L33Z22L11** [comment]
```
 ZhiluBlog  pnpm remove hexo-renderer-marked
 WARN  3 deprecated subdependencies found: cuid@2.1.8, glob@7.2.3, inflight@1.0.6
Packages: -50
--------------------------------------------------
Progress: resolved 184, reused 183, downloaded 0, added 0, done

dependencies:
- hexo-renderer-marked 6.3.0

Done in 1.2s
 ZhiluBlog  pnpm i hexo-renderer-markdown-it-plus
 WARN  3 deprecated subdependencies found: cuid@2.1.8, glob@7.2.3, inflight@1.0.6
Packages: +20                                                                                        
++++++++++++++++++++
Progress: resolved 204, reused 203, downloaded 0, added 20, done

dependencies:
+ hexo-renderer-markdown-it-plus 1.0.6

Done in 1.9s
 ZhiluBlog  hexo clean; hexo serve
INFO  Validating config
INFO  Welcome to Stellar 1.28.1
DOCS  https://xaoxuu.com/wiki/stellar/
REPO  https://github.com/xaoxuu/hexo-theme-stellar.git

INFO  Deleted database.
INFO  Validating config
INFO  Welcome to Stellar 1.28.1
DOCS  https://xaoxuu.com/wiki/stellar/
REPO  https://github.com/xaoxuu/hexo-theme-stellar.git

INFO  Start processing
(node:24072) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
```

![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/33976233/2975b8ca-1009-4b42-b85a-b64c5c1ae2b0)

未能复现问题。试试 `npm update --save` 后执行 `hexo clean; hexo serve`。
