### ISSUE TITLE
期望加入页面搜索功能呢

### ISSUE THREAD

**Issue by wungjyan** [xaoxuu/hexo-theme-stellar#49]
感觉这两个功能还是挺重要的。

我本来想在作者的博客里搜索一些东西，发现没有搜索功能，然后图片不能点击放大预览，有点影响。

希望作者大大有时间考虑下这两个功能。

主题很nice！

**Comment by xaoxuu** [comment]
图片放大功能已支持：
https://xaoxuu.com/wiki/stellar/tag-plugins/#%E6%94%AF%E6%8C%81-Fancybox-%E6%8F%92%E4%BB%B6%E7%82%B9%E5%87%BB%E6%94%BE%E5%A4%A7

搜索功能将会在2.0版本开始支持

**Comment by xaoxuu** [comment]
1.17.0已支持搜索
