### ISSUE TITLE
侧边栏背景可以用自己本地img文件夹里的图片吗？

### ISSUE THREAD

**Issue by Avalon1997** [xaoxuu/hexo-theme-stellar#494]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

侧边栏背景可以用自己本地img文件夹里的图片做背景吗？
我设置了自己本地的图片作背景，然后发现没有任何显示呢

![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/89969876/bb5cdab7-3486-40a5-909c-cc5e8671295c)

**Comment by gsh1209** [comment]
可以


目录结构：
![image](https://github.com/user-attachments/assets/38136063-77ad-467e-a23d-f634c8176069)
配置写法：
![image](https://github.com/user-attachments/assets/2b77bc80-1da9-4899-b539-558af5d47edb)

**Comment by Avalon1997** [comment]
> 可以
> 
> 目录结构： ![image](https://private-user-images.githubusercontent.com/113790912/349523851-38136063-77ad-467e-a23d-f634c8176069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjc3ODgsIm5iZiI6MTcyMTI2NzQ4OCwicGF0aCI6Ii8xMTM3OTA5MTIvMzQ5NTIzODUxLTM4MTM2MDYzLTc3YWQtNDY3ZS1hMjNkLWY2MzRjODE3NjA2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMTUxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjgwNmIyZDg5OGNhYWZjNjUyZTA5M2M0ZGY2YWY2ZmFjMmNkOTJmMWE3MDBjMWVmYThkYjgxMGIxMjU4ZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.leKFuwsUsAzOI6EI80nGVWR5yLJCiyvQr5dgky8MDVI) 配置写法： ![image](https://private-user-images.githubusercontent.com/113790912/349524049-2b77bc80-1da9-4899-b539-558af5d47edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjc3ODgsIm5iZiI6MTcyMTI2NzQ4OCwicGF0aCI6Ii8xMTM3OTA5MTIvMzQ5NTI0MDQ5LTJiNzdiYzgwLTFkYTktNDg5OS1iNTM5LTU1OGFmNWQ0N2VkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMTUxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGY1YjUwNTkzMjYxMDU4ODg2NTI3ZDQ5M2JlMzE3ZWEyY2VlYjFkYWMzMDYwNGU0ODU1ZjdlNmY5OWNkOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YqmvxWqMBLwAVFAMl0v4AI8t806MGmhXcNB6F-r7Rq8)

啊，解决了！！！

**Comment by Avalon1997** [comment]
> 可以
> 
> 目录结构： ![image](https://private-user-images.githubusercontent.com/113790912/349523851-38136063-77ad-467e-a23d-f634c8176069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjc3ODgsIm5iZiI6MTcyMTI2NzQ4OCwicGF0aCI6Ii8xMTM3OTA5MTIvMzQ5NTIzODUxLTM4MTM2MDYzLTc3YWQtNDY3ZS1hMjNkLWY2MzRjODE3NjA2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMTUxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjgwNmIyZDg5OGNhYWZjNjUyZTA5M2M0ZGY2YWY2ZmFjMmNkOTJmMWE3MDBjMWVmYThkYjgxMGIxMjU4ZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.leKFuwsUsAzOI6EI80nGVWR5yLJCiyvQr5dgky8MDVI) 配置写法： ![image](https://private-user-images.githubusercontent.com/113790912/349524049-2b77bc80-1da9-4899-b539-558af5d47edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjc3ODgsIm5iZiI6MTcyMTI2NzQ4OCwicGF0aCI6Ii8xMTM3OTA5MTIvMzQ5NTI0MDQ5LTJiNzdiYzgwLTFkYTktNDg5OS1iNTM5LTU1OGFmNWQ0N2VkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMTUxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGY1YjUwNTkzMjYxMDU4ODg2NTI3ZDQ5M2JlMzE3ZWEyY2VlYjFkYWMzMDYwNGU0ODU1ZjdlNmY5OWNkOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YqmvxWqMBLwAVFAMl0v4AI8t806MGmhXcNB6F-r7Rq8)

啊，解决了！！！！
谢谢！！！
