### ISSUE TITLE
How to hide the banner of the homepage?

### ISSUE THREAD

**Issue by Avalon1997** [xaoxuu/hexo-theme-stellar#499]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

How to hide the banner of the homepage?
I dont want a banner in the top of homepage, how can i hide or delete it ?
<img width="1127" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/89969876/13d2e191-6edb-4b60-9b9a-34615bf69fb1">
我怎样才能把主页的banner隐藏或者删掉呢？

**Comment by thun888** [comment]
`front-matter`里添加`breadcrumb: false`

**Comment by Avalon1997** [comment]
> `front-matter`里添加`breadcrumb: false`

Thanks a lot！！
