### ISSUE TITLE
表达类组件【Copy 复制行】无法像代码块一样当代码过长时能够横向滑动查看

### ISSUE THREAD

**Issue by MaroBytes** [xaoxuu/hexo-theme-stellar#500]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

使用的浏览器：
1. IOS平台下的Safari
2. Windows平台下的Chrome及Edge

操作复现：
1. 电脑网页端：在一条长代码复制块，将鼠标移动至复制块上方，无任何左右滑动条显现
2. 手机网页端：手指试图滑动复制块，但无任何反应，无法查看右侧被隐藏的部分
3. 额外的问题：鼠标和手指点击复制块，会出现光标，可以通过外部输入对复制块进行编辑（类似于HTML元素编辑，但不会保存）

**Comment by xaoxuu** [comment]
设计如此

**Comment by MaroBytes** [comment]
就是说复制块是设计成不能滑动查看对吧(╥﹏╥;)

**Comment by MaroBytes** [comment]
可是无法左右滑动查看，编辑起来是不是也稍显麻烦了些|･ω･｀)

**Comment by xaoxuu** [comment]
适用于这种场景，不要放太长的东西：

<img width="421" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/2859d951-20fa-4810-a4f9-5870c00e536c">

如果东西很多，建议用代码块，那个一样能复制。

**Comment by MaroBytes** [comment]
明白啦，感谢！
