### ISSUE TITLE
空wiki项目导致其它Wiki无法正常显示

### ISSUE THREAD

**Issue by WMD001** [xaoxuu/hexo-theme-stellar#509]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

## 现象

创建有三个wiki，其中有一个wiki目录下是空的，没有对应的文件，启动后只显示一个wiki

## 问题

经过console调试，发现问题出现在如下代码：
```javascript
    let id = wiki_list[i];
    let item = wiki.tree[id]
    let sub_pages = wiki_pages.filter(p => p.wiki === id)
    if (!sub_pages || sub_pages.length == 0) {
      wiki_list.splice(i, 1)
      delete wiki.tree[id]
      continue
    }
```
该代码位于 `stellar/scripts/events/lib/doc_tree.js` 98行，问题出现在 `delete wiki.tree[id]` ，由于检测到wiki目录下没有页面，所以在循环中删除了元素，导致元素下标发生了变化，其它wiki无法正常获取。

目前在空目录下添加新的空页面可以免除此错误。但我觉得不应在循环中执行删除元素的操作。

**Comment by weekdaycare** [comment]
确实在某种情况下空wiki会导致其他wiki读取出错，我试了试倒序遍历 `wiki_list`，可以安全地删除元素而不影响未处理的索引
