### ISSUE TITLE
新建列表页面

### ISSUE THREAD

**Issue by biaoxiaoa** [xaoxuu/hexo-theme-stellar#51]
我想建一个美文选项，点击后出现一个跟首页一样的列表页面。
在article目录下新建index.md这样写的
---
menu_id: article
layout: post
post: Article
---

article目录下新建一个文章test.md这样写
---
menu_id: article
layout: post
post: Article
title: 这是一个美文
---

点击美文后，列表页面是空白的，没有出现新建的美文文章。

**Comment by xaoxuu** [comment]
目前没有列表页面的布局模板，你可以通过设置文章的 `categories` 来分类。
