### ISSUE TITLE
为什么标题默认是日期呀？不应该是一级标题吗

### ISSUE THREAD

**Issue by licoba** [xaoxuu/hexo-theme-stellar#513]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

![image](https://github.com/user-attachments/assets/4847588f-6b94-49ad-97b9-125439a17064)

**Comment by licoba** [comment]
![image](https://github.com/user-attachments/assets/17aa2a9c-66bb-4b48-b711-552e40cd3886)

**Comment by gsh1209** [comment]
这个情况是符合预期的，[代码](https://github.com/xaoxuu/hexo-theme-stellar/blob/7321d7cd8ddc963044386ab075234de3d25c53d0/layout/_partial/main/post_list/post_card.ejs#L49)

原因是你的文章中缺少front-matter，导致找不到`post.title`，使用文件创建日期生成了文章标题

修复方法是补充必要的front-matter字段即可

- [参考1](https://hexo.io/zh-cn/docs/front-matter)
- [参考2](https://xaoxuu.com/wiki/stellar/pages/#%E6%96%87%E7%AB%A0%E6%A8%A1%E6%9D%BF)

**Comment by licoba** [comment]
> 这个情况是符合预期的，[代码](https://github.com/xaoxuu/hexo-theme-stellar/blob/7321d7cd8ddc963044386ab075234de3d25c53d0/layout/_partial/main/post_list/post_card.ejs#L49)
> 
> 原因是你的文章中缺少front-matter，导致找不到`post.title`，使用文件创建日期生成了文章标题
> 
> 修复方法是补充必要的front-matter字段即可
> 
> * [参考1](https://hexo.io/zh-cn/docs/front-matter)
> * [参考2](https://xaoxuu.com/wiki/stellar/pages/#%E6%96%87%E7%AB%A0%E6%A8%A1%E6%9D%BF)

好的谢谢，原因我明白了，但是Hexo的默认Title，他的值是文件名呀，stellar主题是不是也应该Hexo的标准来设计比较好？我用hexo默认的主题，值其实也是文件名

![image](https://github.com/user-attachments/assets/f66c06fd-a699-4256-bd6d-177bab346581)

**Comment by gsh1209** [comment]
hexo的主题单元测试只要求了能够处理没有标题的文章，但没要求如何处理 
- https://github.com/hexojs/hexo-theme-unit-test?tab=readme-ov-file#post

如果是`hexo new`创建的文章，默认是会有front-matter的，
所以还是加上front-matter比较好，其他的文章配置总是要用到front-matter的
