### ISSUE TITLE
Notes 中某个项目的主页目录顶部显示`...`

### ISSUE THREAD

**Issue by Cactusinhand** [xaoxuu/hexo-theme-stellar#516]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

![image](https://github.com/user-attachments/assets/30e27c6d-cb4f-4c5c-b5f0-1fd2fbbff359)

起初以为是我的设置问题，但后来无意间发现别人的博客也有这个问题。
我推测大概是 tree 这个 widget 的问题？

**Comment by xaoxuu** [comment]
这个代表此分组没有标题，有空我改成留空吧
