### ISSUE TITLE
是否考虑支持文章的阅读量显示？

### ISSUE THREAD

**Issue by Sanzro-Lee** [xaoxuu/hexo-theme-stellar#52]
我想看到文章的阅读量显示，试了试LeanCloud，没有成功，但看到主题设置 _config.yml 中 Valine 这一项，所以想问问是否会加这个功能。

[测试的方法来源](https://caixiaobai.github.io/2019/11/17/hexo-%E5%8D%9A%E5%AE%A2%E6%B7%BB%E5%8A%A0%E8%AF%84%E8%AE%BA%E5%92%8C%E9%98%85%E8%AF%BB%E9%87%8F/)

谢谢你制作这么好用又好看的的 hexo 主题

**Comment by xaoxuu** [comment]
value评论官方是支持这个功能的

**Comment by Sanzro-Lee** [comment]
> 
你指的value评论官方是？

**Comment by xaoxuu** [comment]
valine.is.org

**Comment by Sanzro-Lee** [comment]
> valine.is.org

谢谢

**Comment by Sanzro-Lee** [comment]
> 

valine.js.org
