### ISSUE TITLE
火狐浏览器侧边栏滚动条未隐藏

### ISSUE THREAD

**Issue by Abyssknight** [xaoxuu/hexo-theme-stellar#59]
![image](https://user-images.githubusercontent.com/29292466/151654896-51e363cb-b785-4b7b-abee-f3772dc8708b.png)

**Comment by xaoxuu** [comment]
目前不知道怎么兼容火狐

**Comment by YidaozhanYa** [comment]
在火狐浏览器中不仅是侧栏有白条，主页主栏上方也会有一条。
![图片](https://user-images.githubusercontent.com/73830635/164251115-53232455-8685-43f2-ba65-71892c688065.png)

**Comment by MicDZ** [comment]
用`scrollbar-width: none`好像可以解决
