### ISSUE TITLE
Toc怎么层级折叠、URL设置

### ISSUE THREAD

**Issue by Chentongda** [xaoxuu/hexo-theme-stellar#62]
**大佬，请问在侧边栏目录种怎么样可以层级折叠**

还有地址栏上后面这个 `index.html` 要怎么样去掉呢

![image](https://user-images.githubusercontent.com/48764946/153908209-8e600248-4318-4b30-8919-1f34bbad9cb5.png)

**Comment by xaoxuu** [comment]
不可以折叠；
https://hexo.io/docs/configuration 这里有配置

**Comment by Chentongda** [comment]
> 不可以折叠； https://hexo.io/docs/configuration这里有配置

好的，感谢大大
