### ISSUE TITLE
文章的宽度是否可以由用户自定义？或者默认更宽一些？

### ISSUE THREAD

**Issue by stark-zhang** [xaoxuu/hexo-theme-stellar#63]
如题，有些较长的数学公式渲染后和标号重叠了
![image](https://user-images.githubusercontent.com/17326718/155052007-2c4a0cb9-7102-4dd6-b253-a677aaf782f2.png)

**Comment by xaoxuu** [comment]
修改3处的 `--width-main` 即可：
https://github.com/xaoxuu/hexo-theme-stellar/blob/3ada269c686e23c598138e2611261c7c3e8f16d4/source/css/_custom.styl#L65-L78

**Comment by stark-zhang** [comment]
主题是否可以加载`blog/source/_data`下的自定义的`.styl`文件呢，就像next主题一样？直接修改`node_modules/`下的源文件不太合适
