### ISSUE TITLE
生成的url没有后缀/

### ISSUE THREAD

**Issue by chaofanx** [xaoxuu/hexo-theme-stellar#74]
我是用腾讯云对象存储(cos)托管的静态网站，部署后首页生成的`标签`等url没有后缀`/`，导致报错
![image](https://user-images.githubusercontent.com/60053994/166418520-8a6a0d5e-3e0f-4734-a3ae-c2733eca1a57.png)
请问怎么添加后面的斜杠

**Comment by Fairy-a** [comment]
手动 添加上`/`就可以访问

**Comment by chaofanx** [comment]
> 你参考下我的config，有个hexo配置 Message ID: ***@***.***>

![image](https://user-images.githubusercontent.com/60053994/166464012-4f1c251c-d3f1-4021-bf56-3ff9c9d9aeda.png)
指的是这里吗，这里是有`/`的，其他地方我好像没找到配置这个的地方

**Comment by xaoxuu** [comment]
https://hexo.io/zh-cn/docs/configuration
<img width="764" alt="image" src="https://user-images.githubusercontent.com/16400144/167803011-8ee5a863-201f-4bb6-82d3-f741526f9c4a.png">

**Comment by xaoxuu** [comment]
还有就是，你的文件路径是这样吗：`.../categories/index.md`
