### ISSUE TITLE
sidebar.menu下nodes换成friends，more换成about点击后就没有active了

### ISSUE THREAD

**Issue by nnocase** [xaoxuu/hexo-theme-stellar#76]
如何设置按钮的active呢

**Comment by xaoxuu** [comment]
发一下你的 friends 页面的 `front-matter`

**Comment by nnocase** [comment]
---
robots: noindex,nofollow
sitemap: false
menu_id: more
seo_title: 友链
toc_title: 友链索引
comment_title: 快来交换友链吧～
comment_id: '留言板'
---


> 发一下你的 friends 页面的 `front-matter`

**Comment by xaoxuu** [comment]
加上 menu_id: friends

**Comment by nnocase** [comment]
OK，谢谢
