### ISSUE TITLE
文本修饰标签bug

### ISSUE THREAD

**Issue by chaofanx** [xaoxuu/hexo-theme-stellar#83]
当我使用{% emp 着重号 %}标签时，如果标签前面没有文字，那么就会有显示问题
```markdown
{% emp 着重号 %} 标签
这是{% emp 着重号 %} 标签
```

![image](https://user-images.githubusercontent.com/60053994/170831007-2c20386f-3e00-4afb-96c3-e368ed286f85.png)
试了好几遍都这样

**Comment by xaoxuu** [comment]
好像是这样的，你先注意一下吧

**Comment by xaoxuu** [comment]
先这样写： `<emp>着重号</emp>标签`

**Comment by chaofanx** [comment]
> 先这样写： `<emp>着重号</emp>标签`

好的，目前通过前面添加`-`，不是特别影响

**Comment by xaoxuu** [comment]
<img width="176" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/34a11513-24cd-4f20-9fc6-b51e42f8eb1d">

我试了下现在顶格写似乎没有问题了
