### ISSUE TITLE
引用（quot）标签bug

### ISSUE THREAD

**Issue by chaofanx** [xaoxuu/hexo-theme-stellar#84]
当使用两个相同内容的quot标签时，目录显示会有问题，把相同内容的全部高亮

![image](https://user-images.githubusercontent.com/60053994/170860688-2dbf55d7-96e4-42bb-8176-ae479f1e39b7.png)

**Comment by xaoxuu** [comment]
目前确实会存在这个问题，不太好改，你先避免重复使用吧，用在需要强调引用的地方。这个bug先挂着，我有时间了看看怎么改。

**Comment by xaoxuu** [comment]
这个问题不想处理了
