### ISSUE TITLE
nav沒有active的效果

### ISSUE THREAD

**Issue by KvN1027** [xaoxuu/hexo-theme-stellar#85]
我的stellar主題是自行clone的
about頁面是用`hexo new page about`創建
但切換到/about/ 目錄時menu的nav卻沒有active的效果，請問該如何解決或者正確創立page呢，感謝。

**Comment by KvN1027** [comment]
原來是config設定錯了
原代碼
` ` `  
about: '[關於我](/about/)'
` ` ` 
正確代碼
` ` `   
more: '[關於我](/about/)'
` ` ` 
誠摯地感謝🙏

**Comment by xaoxuu** [comment]
如果 `config.yaml` 里用 `about: xxx` 的话，要高亮的页面文件就要写： `menu_id: about`
