### ISSUE TITLE
怎么给文章分类

### ISSUE THREAD

**Issue by King-Eric** [xaoxuu/hexo-theme-stellar#86]
怎么增加分类页？

**Comment by xaoxuu** [comment]
文档第一页第一个标题就有链接：

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/16400144/171107832-65096190-7a1c-4f0c-9b4e-2c9af9ea0b97.png">

**Comment by xaoxuu** [comment]
那个是自动的，不需手动添加，分类的依据是文章的 `categories`，从你的截图可以看到，你的 `categories` 填写格式有误，还是建议先通读 hexo 官方文档和 stellar 官方文档（两个文档里都有分类填写的示例）。
