### ISSUE TITLE
线上环境失效问题

### ISSUE THREAD

**Issue by kongxiyi** [xaoxuu/hexo-theme-stellar#93]
因为需要使用npm i，所以源文件应该都在node_modules中，但是hexo d命令上传默认不上传该文件夹，导致线上版本会造成主题失效，如下图所示，不知道该怎么解决...
![image](https://user-images.githubusercontent.com/62090058/172767307-87b00f53-ddc2-439f-b779-310e5d34f026.png)

**Comment by xaoxuu** [comment]
跟环境无关，大概率是配置的root不匹配导致的
