### ISSUE TITLE
请问怎样才能设置侧边栏显示

### ISSUE THREAD

**Issue by Avalon1997** [xaoxuu/hexo-theme-stellar#95]
我这边在 blog\source\_data 文件夹下创建了 widgets.yml 文件，但是博客网站并没有显示。
![image](https://user-images.githubusercontent.com/89969876/172822914-44406112-f825-41fe-8239-5aa341b28f5c.png)

**Comment by xaoxuu** [comment]
发一下这个文件的完整路径和内容 Message ID: ***@***.***>

**Comment by Avalon1997** [comment]
呃这个问题我昨天解决了...

**Comment by Avalon1997** [comment]
Well ... I solved this problem yesterday
I removed the widgets.yml and added some config in the _config.stellar.yml  XD
There is another problem that bothers me. How can I use wiki ... ?
![image](https://user-images.githubusercontent.com/89969876/173010288-b6726f35-0907-463d-bdb9-a5ab00c8bc08.png)
Just use the command : hexo new page "wiki"   ... ?
