### ISSUE TITLE
github卡片有时存在样式问题

### ISSUE THREAD

**Issue by Frederick-X** [xaoxuu/hexo-theme-stellar#96]
复现：
```
{% ghcard grpc/grpc %}
```

![CleanShot 2022-06-13 at 23 53 19@2x](https://user-images.githubusercontent.com/105006121/173394499-d86345ab-1275-45c6-9347-d032875b2c03.png)

**Comment by xaoxuu** [comment]
这个是 https://github.com/anuraghazra/github-readme-stats 本身的限制，建议描述不要写太长。
