### ISSUE TITLE
怎样才能设置文章隐藏

### ISSUE THREAD

**Issue by Avalon1997** [xaoxuu/hexo-theme-stellar#97]
Hi , how to set the article to hide ?
I tried to write "hide: true" in the front-matter of the post , but it doesn't work.

你好，怎样才能设置文章隐藏呢？
我尝试了在 front-matter 里写入 hide: true ，但是并不起作用。
![图片](https://user-images.githubusercontent.com/89969876/173540041-b4dc8efe-715c-47a3-bd91-b779bc889d6a.png)

**Comment by xaoxuu** [comment]
你在哪里看到要写 `hide: true` 的？目前还没有提供这样的功能，一切以文档为主：https://xaoxuu.com/wiki/stellar/
