### ISSUE TITLE
怎样可以设置文章页面顶部显示横图呢

### ISSUE THREAD

**Issue by Avalon1997** [xaoxuu/hexo-theme-stellar#98]
How to display an image at the top of a post ?

怎样才能在文章页面顶部显示图片呢？
![图片](https://user-images.githubusercontent.com/89969876/173554228-d234c381-2516-4f6a-9b68-548ef2f18004.png)

**Comment by xaoxuu** [comment]
```yaml
banner: url
```

**Comment by Avalon1997** [comment]
Thanks !!!
